### ISSUE TITLE
Trying to upgrade from vw-jni-8.2.0 to something close to vw-jni-8.4.1-SNAPSHOT

### ISSUE THREAD

**Issue by pferrel** [JohnLangford/vowpal_wabbit#1305] opened 2017-08-03 23:17 UTC
Using VW 8.4.0 installed with brew I created a simple test set initializing VW with

    $ vw --csoaa 10  -b 24  --l2 0.0  -l 0.1  -c -k --passes 100  -f /Users/pat/big-data/harness/models/test_resource  --save_resume

Then I paste examples in: 

```
0:0.0 1:1.0 | user_user_2 testGroupId_1 
0:0.0 1:1.0 | user_user_2 testGroupId_1 
0:0.0 1:1.0 | user_user_2 testGroupId_1 
0:0.0 1:1.0 | user_user_2 testGroupId_1 
0:1.0 1:0.0 | user_user_1 testGroupId_1 
0:1.0 1:0.0 | user_user_1 testGroupId_1 
0:1.0 1:0.0 | user_user_1 testGroupId_1 
0:1.0 1:0.0 | user_user_1 testGroupId_1 
save_
```

at the `save_` the file Users/pat/big-data/harness/models/test_resource is updated&mdash;all is well.

Using the last available JNI binary wrapper for 8.2.0 doing the same thing from Java does not update the model file. I'm not running in `--quiet` mode and there is no complaint from VW.

The `save_` pseudo example does apparently work for 8.2.0 since another user is using it in CLI and daemon mode.  

Is this feature not supported with JNI?

On the advice of @arielf it appears I need something like vw-jni-8.4.1-SNAPSHOT so trying to build for dev machine (MBP) and deploy machine (ubuntu). Dev machine first.

**Comment by pferrel** [comment] 2017-08-03 23:24
My excuse for using 8.2.0 in Java and 8.4.0 from the CLI is that I'm having trouble building the JNI wrapper. Which I will solve if the versions here matter.

**Comment by pferrel** [comment] 2017-08-04 04:52
It sounds like getting JNI for 8.4.x may be the key. I have VW built but the comments talk about running `build.sh` to crate the Java stuff and the pom and Makefile don't seem to be sufficient. Will look back in tags to see what happened to it unless you have some ideas.

**Comment by pferrel** [comment] 2017-08-04 21:58
I’m trying to build the JNI wrapper for 8.4.1-SNAPSHOT (master head). I have 8.4.0 running as installed by brew on macOS. With this I have verified my config, input and queries and that “save_” works as expected.

There was a patch made to the brew formula for 8.4.0 to get it to build (some missing include?) I’ve lost the discussion with the brew people and don’t see anything obvious in the few commits to master since 8.4.0.  So I got the latest master and though it builds without the same errors as tag 8.4.0 no binaries are created (complete make log below)

What was the change to get brew working, maybe I need it here?


The last few lines of `make all` output for 8.4.1-SNAPSHOT (master head)
==================================================================

full log here: https://gist.github.com/pferrel/d1ba38520fc9d516574d2eee9f49d53a

ld: warning: directory not found for option '-L/lib'
depbase=`echo ezexample_predict.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DHAVE_CONFIG_H -I. -I../vowpalwabbit    -I/usr/local/include -I/include -D_THREAD_SAFE  -I ../rapidjson/include -stdlib=libc++ -std=gnu++11 -MT ezexample_predict.o -MD -MP -MF $depbase.Tpo -c -o ezexample_predict.o ezexample_predict.cc &&\
	mv -f $depbase.Tpo $depbase.Po
/bin/sh ../libtool  --tag=CXX   --mode=link g++ -I/usr/local/include -I/include -D_THREAD_SAFE  -I ../rapidjson/include -stdlib=libc++ -std=gnu++11 -L/usr/local/lib -lboost_program_options-mt -L/lib -lz -lpthread  -o ezexample_predict ezexample_predict.o ../vowpalwabbit/libvw.la ../vowpalwabbit/liballreduce.la 
libtool: link: g++ -I/usr/local/include -I/include -D_THREAD_SAFE -I ../rapidjson/include -stdlib=libc++ -std=gnu++11 -o .libs/ezexample_predict ezexample_predict.o -Wl,-bind_at_load  -L/usr/local/lib -L/lib ../vowpalwabbit/.libs/libvw.dylib /Users/pat/vw/vowpalwabbit/.libs/liballreduce.dylib ../vowpalwabbit/.libs/liballreduce.dylib -lboost_program_options-mt -lz -lpthread
ld: warning: directory not found for option '-L/lib'
make[1]: Nothing to be done for `all-am'.

**Comment by pferrel** [comment] 2017-08-04 22:39
the 8.4.0 tag gives the following errors:

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I/usr/local/include -I/include -D_THREAD_SAFE -Wall -Wno-unused-local-typedefs -pedantic -stdlib=libc++ -I ../rapidjson/include -O3 -fomit-frame-pointer -DNDEBUG -std=gnu++11 -MT vwdll.lo -MD -MP -MF .deps/vwdll.Tpo -c vwdll.cpp  -fno-common -DPIC -o .libs/vwdll.o
vwdll.cpp:41:28: error: no member named 'codecvt_utf8_utf16' in namespace 'std'
        std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t> convert;
                             ~~~~~^
vwdll.cpp:41:55: error: expected '(' for function-style cast or type construction
        std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t> convert;
                                                     ~~~~~~~~^
vwdll.cpp:41:56: error: expected unqualified-id
        std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t> convert;
                                                              ^
vwdll.cpp:42:9: error: use of undeclared identifier 'convert'
        return convert.to_bytes(utf16_string);
               ^

**Comment by arielf** [comment] 2017-08-04 22:51
Trying to give a helping hand here...

I think before going into `automake.sh` `libtool` and all the issues this tool-chain brings in (which is why I always avoid it when building, I only use simple `make ...` using the default Makefile's).

There seems to be a fundamental issue with the Java build
`jni.h` is missing:

```
$ make java
cd vowpalwabbit; make -j 8 things
make[1]: Entering directory '/home/user/src/vowpal_wabbit/arielf/vowpalwabbit'
make[1]: Nothing to be done for 'things'.
make[1]: Leaving directory '/home/user/src/vowpal_wabbit/arielf/vowpalwabbit'
cd java; make things
make[1]: Entering directory '/home/user/src/vowpal_wabbit/arielf/java'
ver=$(grep AC_INIT ../configure.ac | cut -d '[' -f 3 | cut -d ']' -f 1) && \
newVer=$(perl -e "@a=split('\.', '$ver'); \$a[2]++; print(join('.', @a))") && \
perl -pi -e "s/(\s*)<version>.*-SNAPSHOT/\1<version>$newVer-SNAPSHOT/" pom.xml
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c src/main/c++/vowpalWabbit_learner_VWActionProbsLearner.cc -o src/main/c++/vowpalWabbit_learner_VWActionProbsLearner.o -I /include -I /include/linux
In file included from src/main/c++/vowpalWabbit_learner_VWActionProbsLearner.cc:1:0:
src/main/c++/vowpalWabbit_learner_VWActionProbsLearner.h:2:17: fatal error: jni.h: No such file or directory
compilation terminated.
Makefile:49: recipe for target 'src/main/c++/vowpalWabbit_learner_VWActionProbsLearner.o' failed
make[1]: *** [src/main/c++/vowpalWabbit_learner_VWActionProbsLearner.o] Error 1
make[1]: Leaving directory '/home/user/src/vowpal_wabbit/arielf/java'
Makefile:121: recipe for target 'java' failed
make: *** [java] Error 2
```

(Contrast this with `make python` which just works.)

So the 1st question for all the java layer developers ( @jmorra  @deaktator ?) is:  is `jni.h` supposed to be in the tree? Was it left out by mistake? Does it come with some undocumented prereq?  Thanks!

**Comment by pferrel** [comment] 2017-08-04 22:58
I think the error in the mac build is known and solved from this dicussion: https://github.com/JohnLangford/vowpal_wabbit/issues/1294

8.4.0 is already patched for mac brew and builds under brew. I used it to verify your "save_" examples. It may be all I need is that patch.

Then following the travis script I can build the JNI wrapper using maven (I hope).

**Comment by ryan-deak-zefr** [comment] 2017-08-05 00:30
@arielf `jni.h` should be included in the standard distribution with OS X: 

```bash
JAVA_APP=$(
  ls -l $(which java) \
  | tr -s '[:blank:]' \
  | cut -d' ' -f11.   \
  | xargs dirname
)
JAVA_DIR=$(greadlink -f ${JAVA_APP}/..)
find $JAVA_DIR -name jni.h
```

```
/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni.h
```

Not sure about other OSs.  It should be part of the JDK.

**Comment by pferrel** [comment] 2017-08-05 00:58
@ryan-deak-zefr @arielf I'm a bit lost not being a C++ dev. I assume @arielf you are saying to build with `make` skipping the `sh autogen.sh --enable-libc++`, which does away with the `java` target.

`make java` seems to work for me from the master's head. But the travis.yml says to run `mvn test -f java/pom.xml` which dies with surefire errors so on the chance these aren't real errors and they just require some surefire update, install or ???, I ran 

```
make install -f java/pom.xml -DskipTests
```

this succeeds reporting: 

```
[INFO] Installing /Users/pat/vw/java/target/vw-jni-8.4.1-SNAPSHOT.jar to /Users/pat/.m2/repository/com/github/johnlangford/vw-jni/8.4.1-SNAPSHOT/vw-jni-8.4.1-SNAPSHOT.jar
```

So I now have the JNI wrapper in the `~/.m2` maven cache.

If I get this going, maybe I can help by updating the wiki documentation?

**Comment by arielf** [comment] 2017-08-05 19:13
Thanks @ryan-deak-zefr 

Looks like the build is too mac specific.  Here's what I tried/did:

Turns out on Ubuntu.  `jni.h` isn't included in OpenJDK (JRE only):
```
$ dpkg -L openjdk-8-jre:amd64 | grep jni
[nothing printed]
```
It exists in Oracle java after the (non-standard) oracle install: 
```
/usr/lib/jvm/java-8-oracle/include/jni.h
```

Step #1 towards a solution: I had to install `openjdk-8-jdk` instead of `openjdk-8-jre` to get it.
Now it is there:
```
/usr/lib/jvm/java-8-openjdk-amd64/include/jni.h
```
This (need `openjdk-8-jdk` to build) should be documented as a prereq.

Still, after getting `jni.h` `make java` fails in `vowpal_wabbit` because the java build doesn't seem to figure out where its standard headers are.

Some more info:
```
$ update-java-alternatives -l
 java-1.8.0-openjdk-amd64       1081       /usr/lib/jvm/java-1.8.0-openjdk-amd64
java-8-oracle                             1081       /usr/lib/jvm/java-8-oracle

$ which java
/usr/bin/java

$ ls -l /usr/bin/java
lrwxrwxrwx 1 root root 22 May  5  2016 /usr/bin/java -> /etc/alternatives/java

$ ls -l /etc/alternatives/java
lrwxrwxrwx 1 root root 46 Aug  5 11:51 /etc/alternatives/java -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

```
The `JAVA_APP` trick to find `JAVA_DIR` is to OS-X specific.  On Ubuntu it fails in multiple places.

`greadlink` doesn't exist on Ubuntu:
```
No command 'greadlink' found, did you mean:
 Command 'readlink' from package 'coreutils' (main)
greadlink: command not found
```

After changing to `readlink` it fails because `JAVA_APP` is wrongly set to `/etc/alternatives` (needs an additional readlink, or better: `-f` argument).

Some ideas on how to do this more portably can be found in:
https://stackoverflow.com/questions/14529720/how-to-make-jni-h-be-found

end-to-end, this works on Ubuntu:
```
$ cat JAVADIR
#!/bin/bash
echo $(dirname $(dirname $(dirname $(readlink -f $(which java))))/../)

$ ./JAVADIR
/usr/lib/jvm/java-8-openjdk-amd64/jre
```

**Comment by deaktator** [comment] 2017-08-05 20:03
@arielf when I commented before (I'm also @ryan-deak-zefr), I did the bash one liners just to show you they exist in the standard JDK install on OS X. I wouldn't use those for the build script. The JDK is necessary for JNI dev. That can be documented better but the need for a JDK shouldn't be surprising to anyone in Java land.

I imagine the way to go is to document that JAVA_HOME must be set and have the VW build use that to find the JNI headers. That should work.

$JAVA_HOME/include/jni.h should exist.

**Comment by pferrel** [comment] 2017-08-05 20:32
continuing...

Bypassing `autogen.sh` to use make directly as in:

 - `make java`
 - `mvn install -f java/pom.xml -DskipTests`

creates a 23k jar so this is not working either. The test failures on `mvn install` may be more significant than I thought. I get no hard errors on `make java` but how would I tell if it really succeeded?

**Comment by pferrel** [comment] 2017-08-05 20:38
I guess to put it simply I don't seem able to build 8.4.0 or master's head on my MBP. Brew works so I tried patches suggested there but they may be in master now. Since I've never built on the mac outside of brew I'm not sure how to verify a build worked.

**Comment by pferrel** [comment] 2017-08-05 20:43
The `mvn install -f java/pom.xml` error 

```
Running vowpalWabbit.ClosingTest
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010f20b062, pid=13157, tid=0x0000000000001c03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.102-b14 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libboost_program_options-mt.dylib+0x1c062]  boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool) const+0x32
```

**Comment by pferrel** [comment] 2017-08-05 21:19
I went to the patch referenced in https://github.com/JohnLangford/vowpal_wabbit/issues/1294 which cooresponds to a commit #c632a1e0907d464f865df72ce06a86cbe481d81e by @JohnLangford When I build this with just `make` no `autogen.sh` I do get a vw_jni.dylib created in the java directory. So the build may well have completed correctly. I get the following `java/target` contents. To properly install this I need to something like put the dylib in some place where it will be loaded by the JNI wrapper????

I keep coming back to the reference for `build.sh` that was once in the java directory. Did it put the dylib somewhere? Could this be why the java tests fail?

```
Maclaurin:vw pat$ ls -al java/target/
total 5088
drwxr-xr-x  14 pat  staff      476 Aug  5 14:09 .
drwxr-xr-x   9 pat  staff      306 Aug  5 14:07 ..
drwxr-xr-x  17 pat  staff      578 Aug  5 14:09 apidocs
drwxr-xr-x   3 pat  staff      102 Aug  5 14:07 classes
drwxr-xr-x   3 pat  staff      102 Aug  5 14:07 generated-sources
drwxr-xr-x   3 pat  staff      102 Aug  5 14:07 generated-test-sources
drwxr-xr-x   4 pat  staff      136 Aug  5 14:09 javadoc-bundle-options
-rwxr-xr-x   1 pat  staff  2439176 Aug  5 14:07 libvw_jni.dylib
drwxr-xr-x   3 pat  staff      102 Aug  5 14:09 maven-archiver
drwxr-xr-x   3 pat  staff      102 Aug  5 14:07 maven-status
drwxr-xr-x   3 pat  staff      102 Aug  5 14:07 test-classes
-rw-r--r--   1 pat  staff   116203 Aug  5 14:09 vw-jni-8.4.1-SNAPSHOT-javadoc.jar
-rw-r--r--   1 pat  staff    17104 Aug  5 14:09 vw-jni-8.4.1-SNAPSHOT-sources.jar
-rw-r--r--   1 pat  staff    21118 Aug  5 14:09 vw-jni-8.4.1-SNAPSHOT.jar
```

**Comment by arielf** [comment] 2017-08-06 01:02
Thanks Ryan,

These simple steps made building the `vw` jni build work for me:
```
$ sudo apt install openjdk-8-jdk
$ export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

# -- In the vowpal_wabbit dir:
$ make java
...
# -- All the build goes smooth and produces this:
-rwxr-xr-x 1 ... ... 3208040 Aug  5 17:47 java/target/libvw_jni.so
```

Pat: please don't use `autogen.sh` it is destructive (running it overwrites original `Makefile`s and invokes `libtool` which has other side effects reported by many to cause issues). It is only there as a last resort for environments where nothing else works.  On Ubuntu it is never needed.

If you already have a destroyed env, try renewing all Makefiles from original source:
```
  git checkout Makefile */Makefile
```
Or maybe better, a fresh git clone from latest sources.  There should be no issues building java with latest and the simple instructions.

**Comment by deaktator** [comment] 2017-08-06 01:47
@arielf no problem. Glad it works. Maybe we should put a README.md in the java directory or something.

**Comment by pferrel** [comment] 2017-08-06 16:09
@arielf @deaktator Thanks, I was able to get there on there mac too. But there are still several things that need to be done to remove differences in how this and the 8.0 and 8.2 vw-jni is used:

 - this requires a build on dev machine and deploy machine, OK, doable, but...
 - the old 8.0.0 and 8.2.0 vw-jni artifact could be added to a project pom.xml and included in your project from the maven-verse and run on mac or ubuntu. This is the desirable way to use a .so or .dylib. The current state of build allows you to import the classes but not execute them without installing the dynamic libs in the system. This is why the maven tests fail I afaict. Embedding the dynamic libs in the jar would be better because...
 - the .so or .dylib has to be installed into the system in different ways on mac and ubuntu.

I'm not familiar with bundling binary executables in jars (not a C dev) but from research there is a way to do this to avoid the extra step of making the dynamic lib a system lib. A way to pull the binary from the jar instead of installing it in some special .so or .dylib path.

The last step is what I'm struggling with now. Do the 8.0 or 8.2 release build scripts still exist? The profile `release-sign-artifacts` exists in the `java/pom.xml` but I can't find what I would guess is some automation script that is run at binary maven-verse release time.

**Comment by arielf** [comment] 2017-08-06 16:37
You can try to statically build and link everything.  I always do it. For the C/C++ parts, instead of `make` you can try:
```
make CXX='g++ -static'
```
This generates executables that never break when upgrading the system. The dev env needs to be only on the build machine, not on the deploy side, plus, the same executable runs on all Linux/Intel distros, including very old ones.

Of course, this doesn't make Mac and Linux compatible, not it can help the java eco system (which I'm not familiar with), but it goes a long way towards long-term stability and pain-free operation on each platform.

**Comment by pferrel** [comment] 2017-08-06 17:40
@arielf that may also be the key to putting the lib in the jar. We do something similar in Apache Mahout for GPU libs, which are C so let me ask the build master there. 

Do you know who releases these binaries for VW? I still suspect there is a CI script somewhere that does this.

**Comment by pferrel** [comment] 2017-08-06 20:14
I've built the VW binary to produce `libvw_jni.dylib` and can get it to execute but both `make test`, `mvn test -f java/pom.xml` and my app cause VW to crash with the error below. Is this a boost version problem? I have Boost 1.64.0 installed from brew, not sure if this is built with `Program_Options::` as required in the VW README.md but it I looks like the options are seen, they are just wrong somehow. 

Are these errors from VW compile time options that are set incorrectly? Could using autogen be required for this? I guess I'll go back to try autogen again.

BTW `make CXX='g++ -static` fails on the mac so going with `libvw_jni.dylib` for now on the mac.



========================================================================
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000127cd8062, pid=23840, tid=0x0000000000005f03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.102-b14 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libboost_program_options-mt.dylib+0x1c062]  boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool) const+0x32
```

**Comment by pferrel** [comment] 2017-08-06 20:37
Went back to the autogen build method but get the same error in `mvn test`:

```Running vowpalWabbit.learner.VWActionProbsLearnerTest
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000012d99b062, pid=30599, tid=0x0000000000001c03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.102-b14 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libboost_program_options-mt.dylib+0x1c062]  boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool) const+0x32
```

**Comment by pferrel** [comment] 2017-08-06 20:56
Stepping into the code with a debugger:

```    
public static <T extends VWLearner> T create(final String command) {
        long nativePointer = initialize(command); <============= here is as far as I can go, the error
                                                                                                              happens in here
        VWReturnType returnType = getReturnType(nativePointer);

        switch (returnType) {
            case ActionProbs: return (T)new VWActionProbsLearner(nativePointer);
            case ActionScores: return (T)new VWActionScoresLearner(nativePointer);
            ...
```

**Comment by deaktator** [comment] 2017-08-06 21:16
@pferrel did you try boost 1.55? I've had more luck with that boost version.

**Comment by arielf** [comment] 2017-08-07 04:46
@pferrel sorry no, I don't knpw who builds these.

Also: boost versions are notoriously incompatible.  You must make sure that you use the same compiler/env for both the libs and the main program you use, so it is highly expected to have a runtime SIGSEGV when they are mixed-up.  This is yet another reason to link statically so your `vw` (and its libs or JNI) is self contained (includes the libboost it was built against).

**Comment by pferrel** [comment] 2017-08-07 19:05
@deaktator I downgraded to Boost 1.55 and have the same problem. 

@arielf I agree, statically linking in Boost, purpose build for VW, would be the best solution. Messing with system dynamic libs may have side effects and you don't really know what you are getting. Is this what the static build in the makefile does? Hacking the VW makefile seems daunting but ok. I assume you are saying I should build Boost locally with certain options?

At this point on macOS I can build but not run VW from source, I can install it with brew and run it but without the `libvw-jni.dylib` or vw_jni jar.

The brew version works brilliantly (apparently with boost 1.64 unless brew uses some static way to include the 1.55 lib), it just doesn't build the`libvw-jni.dylib` or the vw-jni jar.

I just wiped an old MBP and installed Ubuntu 16.04 in the hope this will get me down the road. I've now devoted a month to getting "save_" to work in a debuggable env. Many missteps on my part so your continued help is really appreciated.

**Comment by arielf** [comment] 2017-08-07 22:39
@pferrel 

Here's what I would try on the Mac side:

- Locate the person who did the `brew` packaging
- Ask them to also do `make java` (given the info above) and include the (java JNI) missing pieces in their standard package

Sorry, I don't have enough java / OS-X / brew Fu to help more here.

**Comment by pferrel** [comment] 2017-08-07 22:49
on it, also find how they build, it’s all in ruby so i need help from them to tell what it’s doing.

I now have my old MBP running ubuntu, another day to get everything to work and I’ll have an alternative.

I guess no one is using JNI on a mac. But why was it working in the 8.0 and 8.2 maven packages? Someone in VW knows how to build and release JNI that works anywhere. Does @JohnLangford do all that?

**Comment by jon-morra-zefr** [comment] 2017-08-07 23:03
I co-wrote most of this stuff (along with @deaktator).  I've been busy with a whole bunch of other projects, but I'll try and find time this week to sort all this stuff out for you.  At a real high level the current master underwent a large refactoring on the JNI layer.  More information can be found in #1193, but basically the old versions (before that merge) tried to wrap the JNI code compiled for a bunch of different platforms inside of the packaged jar.  This got unwieldy to manage.  The new version does not do this and relies on a system dependent library be on the `java.library.path`.  This leaves a gaping hole in the deployment process as such a library is at upon compile time and placed in the `java/target` directory.  This is picked up at test time (have a look at the `pom.xml` and check how the `java.library.path` is getting manipulated at test time), but there is currently no process to do this at deploy time.  This is still an open issue.  In house we have compiled the version of the shared library we need and manually place it on the `java.library.path` on machines when we need to.  This makes the Java code platform independent.  Such a scheme will work on both Mac and Linux.

If you're using the new version of VW, the version of Boost doesn't matter.  You should be able to just call the following commands (on a Mac, replace the target directory of the copy for a Linux box).

```
cd ~/git/vowpal_wabbit
make java
cd java
mvn install
cp target/libvw_jni.dylib ~/Library/Java/Extensions
````

Note that the target directory mentioned in the last line was found by issuing the following commands to find my `java.library.path`.

```
jon.morra:vowpal_wabbit/ (master✗) $ scala                                                                                                                                                                               [16:00:04]
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> System.getProperty("java.library.path")
res0: String = /Users/jon.morra/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.

scala> :q
jon.morra:vowpal_wabbit/ (master✗) $      
````

You can (should) find out your own `java.library.path` and put the shared library somewhere appropriate on your own machine.  BTW, the chosen location of the shared library may not exist, if so you should create the directory first.

**Comment by pferrel** [comment] 2017-08-08 01:27
Wow, thanks @jon-morra-zefr this explains a lot. I understand this is from your very small amount of spare time, you answered just the right things and this will save me a lot of time. I can make the so & dylib release model work now that I know how it's supposed to go.

BTW I'm also using Scala for the app.

**Comment by pferrel** [comment] 2017-08-08 16:46
@jon-morra-zefr if you copy the lib before running `mvn install` you will be testing what was just built from C, which I think covers your compile time vs deploy time issue but maybe I misunderstood.

```
cd ~/git/vowpal_wabbit
make java
cd java
cp target/libvw_jni.dylib ~/Library/Java/Extensions # must copy before running tests in mvn
mvn install
```

Which works on macOS, Boost 1.64, and passes tests with some odd log statements that look like errors but may just be how they are worded. There are corrupt cache statements too so I re-ran the install but they don't go away. Maybe this is as expected. In any case they aren't counted as junit errors.  https://gist.github.com/pferrel/e016b350758a349bcdaacf1cc53de536

So ignoring these for now I'll proceed to trying my app. 

And it works!!! I had to replace "save_" with a call to `vw.saveModel(new File(params.modelName))`, which I assume replaces the pseudo example. I have questions about how often or how performant the save is (how often I can get away with checkpointing the online learning model) but for now I'm going to bask in the glory of it all. Thanks @jon-morra-zefr you saved my bacon, the boss was looking at me askance (I'm the boss ;-)

**Comment by jon-morra-zefr** [comment] 2017-08-08 16:48
Those cache errors you're seeing are the JUnit tests works as designed.  We test for bad caches and cannot silence VW errors during test time.

**Comment by pferrel** [comment] 2017-08-08 16:51
I figured but was too excited to read the tests, woohoo! Can't thank you enough.

**Comment by ryan-deak-zefr** [comment] 2017-08-08 16:57
@jon-morra-zefr @pferrel: I wrote the `ClosingTest` and those invalid cache messages are not supposed to be there.  If you look at the [ClosingTest](https://github.com/JohnLangford/vowpal_wabbit/blob/master/java/src/test/java/vowpalWabbit/ClosingTest.java#L175) code, you'll see that each time you ask for a `model(PASSES)`, you should get a new cache file location and caches should not be reused across models.  The fact that the cache files are bad and need to be rebuilt is a bad sign and something I wanted to test for.  The closing code seems pretty finicky so I wanted to go through a bunch of closing scenarios. Perhaps the tests should scrape STDERR and look for those messages and fail.  That's hard though because most of the testing is asynchronous.

**Comment by jmorra** [comment] 2017-08-08 16:58
I stand corrected.

**Comment by pferrel** [comment] 2017-08-08 17:51
@ryan-deak-zefr yeah read the test.  I don't see cache corruption messages in my app, maybe because I don't use `vw.close` only `vw.saveModel(new File(params.modelName))` and this is not during shutdown, except by accident. 

I have multiple models so make no assumptions about cache files--I wasn't sure how to use them in my case. I create an instance of the Java VW learner class per model, learn online for all models, checkpoint the models with every so many examples or on an idle timer.

Does this only affect the cache? Could the model ever be corrupted? If only the cache it can be rebuilt, right? 

Just trying to understand the magnitude of the issue and any work around.

**Comment by pferrel** [comment] 2017-08-10 01:36
Would it help to capture SIGTERM and delay a bit?

**Comment by ryan-deak-zefr** [comment] 2017-08-10 16:45
It might help.  Not sure if the C code emits one or if it just puts out a log message and continues on its merry way.
> Would it help to capture SIGTERM and delay a bit?
>

**Comment by pferrel** [comment] 2017-08-10 16:49
Actually I'd expect to get SIGTERM in my app, not from someone killing VW since we are using it as a lib it could not be stopped with kill, only my app can. Or maybe I missed something.

**Comment by pferrel** [comment] 2017-08-10 17:05
Actually that is redundant, and I would do is `vw.close()` and delay.

**Comment by pferrel** [comment] 2017-08-10 21:56
@arielf did you say you are on Ubuntu 16.04? I can't get zlib1g-dev to install. Mac works now Ubuntu is being cranky. Without the dev version I get `zlib.h` missing so `comp_io.cpp` does not compile. It's my only build error :-(

**Comment by arielf** [comment] 2017-08-10 22:12
Latest LTS is 16.04.3

No issue here.
You must have some messed-up env but without seeing your command and exact error, it is hard to tell.

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

$ uname -a
Linux hostname 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ sudo apt-get install zlib1g-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  zlib1g-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/168 kB of archives.
After this operation, 425 kB of additional disk space will be used.
Selecting previously unselected package zlib1g-dev:amd64.
(Reading database ... 235117 files and directories currently installed.)
Preparing to unpack .../zlib1g-dev_1%3a1.2.8.dfsg-2ubuntu4.1_amd64.deb ...
Unpacking zlib1g-dev:amd64 (1:1.2.8.dfsg-2ubuntu4.1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up zlib1g-dev:amd64 (1:1.2.8.dfsg-2ubuntu4.1) ...
```

**Comment by pferrel** [comment] 2017-08-10 23:46
Thanks for verifying. I looked back in my very short history and had added the chrome apt repo, removed it and now building--I'm so embarrassed.

Now all it good, tests pass.

**Comment by arielf** [comment] 2017-08-11 03:23
Ubuntu "just works" as long as it is not too polluted by non-standard stuff.
Just keep it clean. 

To get chrome (not literally, but almost identical, from same source base):
```
sudo apt install chromium-browser
```

**Comment by pferrel** [comment] 2017-08-11 13:38
Thanks, been using Ubuntu since 2004. I'm always in package hell but it beats what came before--no package manager. We were supposed to target Ubuntu 14.04LTS and FYI there are too many back ports required, so 16.04 seems like the sweet spot.

Not worried about Chrome, it's just out of habit, maybe a bad habit.

**Comment by arielf** [comment] 2017-08-11 16:24
"package hell" on Ubuntu/Debian? This is the 1st time I hear anyone saying this.

I never had an issue.  Switched from RH many years ago. I'm using many languages and often older versions of libraries for backward compatibility (notably boost when C++ is concerned). It's the most boring/always-works installation and configuration environment I've ever used. Supports multi-arch/multilib, default vs personalized configs under /etc. abiilty to move slower (LTS) or faster (latest, and even PPAs) with never a need to build things yourself. It always works.

You must be making some seriously non standard modifications if you encounter problems in installation.  Please share details (e.g. on askubuntu.com) and someone should be able to help.

Maybe you need a clean install if you're encountering issues on a regular basis?

**Comment by JohnLangford** [comment] 2017-11-25 21:05
I'm assuming this one is finished and closing.  Reopen if not so.

**Closed by JohnLangford** 2017-11-25 21:05 UTC
