### ISSUE TITLE
Test 61 failure

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#680] opened 2015-06-07 15:59 UTC
Few weeks ago I've noticed a small bug.  `make test` completes without a problem after first launch, but 2 `lt-vw` processes keeps running as background processes after that. So if you execute `make test` again you'll get 
```
RunTests: test 61: lenient-diff.tmp: line 1: fuzzy-match missing data on one of the sides. Can't compare
                                                                              > bind: Address already in use
RunTests: test 61: saving lenient diff in 'test-61.lenient-diff' for later inspection
RunTests: test 61: FAILED: ref(/dev/null) != stderr(stderr.tmp)
        cmd: /usr/bin/timeout 30 ./daemon-test.sh
```
You'll get this every time till you kill lt-vw processes manually.  As first launch goes fine Travis CI ignores this problem. That's quite annoying to kill these processes every-time if you run make tests often, could someone fix?

**Comment by arielf** [comment] 2015-06-08 18:08
I was looking at this and wasn't able to reproduce in my own (Ubuntu, desktop) env.

Also: I cannot find any 'lt-vw' string anywhere in the vowpalwabbit code or tests

Is this happening only in Travis?

Anyway, I will try to modify `test/daemon-test.sh` so killing of the daemon is more reliable (with a pid file)

**Comment by arielf** [comment] 2015-06-08 18:26
If I use --pid_file ... and only send SIGTERM (via kill) to the process matching the pid in the pidfile, I always get this:
```
11:18 go 455 vowpal_wabbit/arielf> ( cd test/ ; ./daemon-test.sh )
vw-daemon-test: OK
*** Error in `../vowpalwabbit/vw': free(): invalid pointer: 0x00007f215eb8a000 ***
```
So looks like we're still not shutting down properly on SIGTERM to the parent process.  Need to fix this first before we can try fixing `daemon-test.sh`.  Perhaps the two issues are related.

**Comment by trufanov-nok** [comment] 2015-06-08 18:36
> I cannot find any 'lt-vw' string anywhere

I suppose this is an effect of calling system `fork()` function.
I'm observing 2 `lt-vw` processes if I execute
`vw --daemon --num_children 1 --port 10000`   
and 10 processes if just ``vw --daemon``

**Comment by arielf** [comment] 2015-06-08 20:35
Thanks!
That explains it.  Maybe 'lt-' has something to do with linux threads

Although it doesn't happen on my system (Ubuntu 14.04).
When I call:

    `vw --daemon --num_children 1 --port 10000`

I only see two processes both called `vw`.  No `lt-vw` anywhere.

Are you using an older version of Ubuntu?

Can you try the following?
In `test/daemon-test.sh`.  Look for the line that reads:

    `$PKILL -9 -f "$DaemonCmd" 2>&1 | grep -q 'no process found'`

And modify it to:

    `$PKILL -9 -f "(lt-)?$DaemonCmd" 2>&1 | grep -q 'no process found'`

i.e. just add `(lt-)?` just before `$DaemonCmd`.  It should work for both cases since the (lt-)? in the regexp is optional.  I verified that adding this doesn't regress on 14.04.

Does it solve the issue in your env?
(Sorry, can't reproduce here. so need your help).

**Comment by trufanov-nok** [comment] 2015-06-08 21:01
I'm using Kubuntu 15.05 so it's newer.
Anyway appearance of "lt-". might be caused by me. I shall retest with clean fork.

Also, `$PKILL -9 -f "(lt-)?$DaemonCmd" 2>&1 `didn't help. I wonder if it should bcs it seems DaemonCmd is `../vowpalwabbit/vw -t -i vw-daemon-test.model --daemon --num_children 1 --quiet --port 54248`. I've tried $VW instead of it and it failed as `$VW = ../vowpalwabbit/vw `. So I hardcoded `$PKILL -9 -f "(lt-)?vw" 2>&1` and this seems to solve my problem.

**Comment by trufanov-nok** [comment] 2015-06-08 21:13
It seems lt- prefix appeared bcs i did something i don't understand with ./autogen.sh or ./configure while trying to reproduce another problem. And it's related to libtool. I have ltmain.sh in vowpal_wabbit which was generated by something and this script definitely has relation to this prefix. You can also google out something about libtool and lt- prefix: http://www.gnu.org/software/libtool/manual/html_node/Wrapper-executables.html

**Comment by arielf** [comment] 2015-06-08 22:36
Note that hardcoding `$PKILL -9 -f "(lt-)?vw"` is unsafe.  May kill other unrelated `vw` processes on the same machine.

The intention was to only kill the `vw` procs that were started by the `daemon-test.sh` script. Need to include at least the port and numchildren args in `-f ...` to be safe.  That's why it is implemented this way.  Here's a possible cleaner/safer solution:

```
    DaemonPat=`echo -- $DaemonCmd | sed 's/vw/(lt-)?vw/'`
    $PKILL -9 -f "$DaemonPat" 2>&1 | grep -q 'no process found'
```

**Comment by trufanov-nok** [comment] 2015-06-08 23:01
doesn't work either.
I checked running processes
```
truf     27908  0.0  0.0  25588   356 ?        Ss   02:48   0:00 /home/truf/ml/vowpal_wabbit/vowpalwabbit/.libs/lt-vw -t -i vw-daemon-test.model --daemon --num_children 1 --quiet --port 54248
truf     27909  0.0  0.0 103732  4848 ?        Sl   02:48   0:00 /home/truf/ml/vowpal_wabbit/vowpalwabbit/.libs/lt-vw -t -i vw-daemon-test.model --daemon --num_children 1 --quiet --port 54248
```
It uses /.libs/ subfolder as described on the page i referred to above.
>The actual program executable is created below .libs, and its name will end in $(EXEEXT) and may or may not contain an lt- prefix

I missed it ls bcs the folder is hidden.

**Comment by arielf** [comment] 2015-06-09 01:22
Thanks Alex.

OK, this should work better:
```
    DaemonPat=`echo $DaemonCmd | sed 's/^[^ ]*vw /.*vw /'`
    $PKILL -9 -f "$DaemonPat" 2>&1 | grep -q 'no process found'
```
Can you verify? Thanks again.

**Comment by trufanov-nok** [comment] 2015-06-09 07:02
Yes, this one works. Thanks!

**Comment by arielf** [comment] 2015-06-09 17:14
Great. Thanks for confirming.

Do you want me to create a PR or you want to do this and close the issue?
I don't mind either way.

Also, thanks for reporting this. so I guess now we know `lt` stands for `libtool`.

**Comment by trufanov-nok** [comment] 2015-06-09 17:36
Yes, please, create a PR for this.

2015-06-09 21:15 GMT+04:00 Ariel Faigon <notifications@github.com>:

> Great. Thanks for confirming.
>
> Do you want me to create a PR or you want to do this and close the issue?
> I don't mind either way.
>
> Also, thanks for reporting this. so I guess now we know lt stands for
> libtool.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JohnLangford/vowpal_wabbit/issues/680#issuecomment-110437386>
> .
>



-- 
With best regards,
Alexander Trufanov

**Comment by JohnLangford** [comment] 2015-06-14 22:22
This should be fixed now, so closing.

**Closed by JohnLangford** 2015-06-14 22:22 UTC

**Comment by JohnLangford** [comment] 2015-06-14 23:33
Thanks much for working through this.

-John
