### ISSUE TITLE
OSX 10.9.5 build issue

### ISSUE THREAD

**Issue by tristanreid** [JohnLangford/vowpal_wabbit#481] opened 2014-12-30 18:50 UTC
When I pull from master and try to make, I get:
 
In file included from global_data.cc:13:
In file included from ./global_data.h:20:
./learner.h:198:81: error: redefinition of default argument
  template<class T> learner<T>& init_learner(T* dat, base_learner* base, size_t ws = 1)
                                                                                ^    ~
./learner.h:72:81: note: previous definition is here
  template<class T> learner<T>& init_learner(T* dat, base_learner* base, size_t ws = 1);
                                                                                ^    ~
1 error generated.

Please let me know if other information is helpful?

Also, if I build 7.8 it will successfully make, but test 38 fails with 'no such file or directory', and then tests abort at 59 with another No such file or directory, command is undefined.  If I then ignore this and install, I am not able to import pylibvw.  

I'm guessing that all this is related, but unsure of how to proceed.  I'd really appreciate someone could give me pointers on how to troubleshoot.  So far I've uninstalled and re-built boost, I've tried building ezexample_predict directly, I get the following error:

make ezexample_predict
clang++ -std=c++0x    ezexample_predict.cc   -o ezexample_predict
Undefined symbols for architecture x86_64:
  "VW::initialize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      _main in ezexample_predict-0e07c4.o
  "VW::read_example(vw&, char*)", referenced from:
      ezexample::setup_for_predict() in ezexample_predict-0e07c4.o
  "VW::finish_example(vw&, example*)", referenced from:
      ezexample::~ezexample() in ezexample_predict-0e07c4.o
  "VW::new_unused_example(vw&)", referenced from:
      ezexample::get_new_example() in ezexample_predict-0e07c4.o
  "VW::parse_example_label(vw&, example&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      ezexample::set_label(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in ezexample_predict-0e07c4.o
  "VW::add_constant_feature(vw&, example*)", referenced from:
      ezexample::ezexample(vw*, bool, vw*) in ezexample_predict-0e07c4.o
  "VW::finish(vw&, bool)", referenced from:
      _main in ezexample_predict-0e07c4.o
  "vw::learn(example*)", referenced from:
      ezexample::setup_for_predict() in ezexample_predict-0e07c4.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ezexample_predict] Error 1

**Comment by arielf** [comment] 2015-01-01 12:00
Thanks.
The build of latest from master issue is not Mac specific.
I can reproduce the redefinition error on Ubuntu when building with clang++ (builds fine with g++)

Can't reproduce the issues with `make test` in 7.8

**Comment by JohnLangford** [comment] 2015-01-01 14:22
I believe this is fixed now.

Incidentally, clang++ is not the default compiler because on my laptop it
does not play nice with the stl library.  I expect (?) this is a temporary
problem.

-John

**Comment by tristanreid** [comment] 2015-01-02 01:58
Thanks so much for the fast feedback!  Happy New Year!

I notice the second line of autoconf.sh has the effect that even if you specify CXX, it gets overridden by clang++ if clang++ exists on your system:
    [ -x "`which g++`" ] && CXX=g++
    [ -x "`which clang++`" ] && CXX=clang++

If I comment out the second line and run with:
    ./autogen.sh CC=gcc CXX=g++ CXXCPP='g++ -E'

Then make results in this error:

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I/usr/local/include -I/include -D_THREAD_SAFE -O3 -fomit-frame-pointer -ffast-math -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -DNDEBUG -Wall -pedantic -std=c++0x -MT vwdll.lo -MD -MP -MF .deps/vwdll.Tpo -c vwdll.cpp  -fno-common -DPIC -o .libs/vwdll.o
vwdll.cpp: In function 'void VW_Finish(VW_HANDLE)':
vwdll.cpp:55:16: error: 'LEARNER::base_learner' has no member named 'driver'
    pointer->l->driver(pointer);
                ^

My g++ version is 4.9.1...any ideas?  Am I using autogen correctly?

Thanks again,

**Comment by JohnLangford** [comment] 2015-01-03 23:20
This should be fixed now.

-John

**Comment by JohnLangford** [comment] 2015-01-04 01:48
Closing on assumption that it's fixed---reopen otherwise.

**Closed by JohnLangford** 2015-01-04 01:48 UTC

**Comment by tristanreid** [comment] 2015-01-04 03:38
Hey - I think it solved the previous issue, thanks.

I'm now seeing a failure of RunTests 61:

RunTests: test 61: './daemon-test.sh' failed (exitcode=1)
RunTests: exiting with status=1
make: *** [test] Error 1

If I skip that test, it fails on 69:

RunTests: test 69: stderr OK
RunTests: test 69: lenient-diff.tmp: line 1: fuzzy-match missing data on one of the sides. Can't compare
5 4 2 1 3  1.001873  							      <
RunTests: test 69: saving lenient diff in 'test-69.lenient-diff' for later inspection
--- diff -u --minimal train-sets/ref/sequence_data.nonldf.beam.test.predict sequence_data_beam.predict
--- train-sets/ref/sequence_data.nonldf.beam.test.predict	2015-01-03 16:55:45.000000000 -0800
+++ sequence_data_beam.predict	2015-01-03 19:35:09.000000000 -0800
@@ -2,8 +2,8 @@
 5 4 3 2 4  1.000000
 5 4 3 2 5  1.000000
 5 3 2 1 3  1.001872
-5 4 2 1 3  1.001873
 5 4 3 1 3  1.001873
+5 4 2 1 3  1.001873
 5 3 2 1 4  1.011277
 5 3 2 1 2  1.767606
 5 4 2 1 2  1.767607
RunTests: test 69: FAILED: ref(train-sets/ref/sequence_data.nonldf.beam.test.predict) != predict(sequence_data_beam.predict)
	cmd: ../vowpalwabbit/vw -d train-sets/sequence_data -t -i models/sequence_data.model -p sequence_data_beam.predict --search_beam 10 --search_kbest 10

**Comment by JohnLangford** [comment] 2015-01-04 03:45
I'm not sure what's up with the daemon test.  Do you need daemon mode?

For the other, this is a low-order precision problem.  These are common 
due to slightly different ways of doing floating point arithmetic on 
different machines/libraries.  Try:

./RunTests -d -f -E 0.001

-John

**Comment by tristanreid** [comment] 2015-01-04 21:29
Looks good!  Thanks, I hadn't noticed those usage messages in RunTests.

I don't need daemon mode, I'm all set.  If you ever need to revisit it, I'll be happy to help troubleshoot, as someone who can replicate.
