### ISSUE TITLE
Build failure on Ubuntu 15.10

### ISSUE THREAD

**Issue by usptact** [JohnLangford/vowpal_wabbit#842] opened 2015-10-28 04:44 UTC
Gettting the following error while building the latest VW from sources on Ubuntu 15.10:

libtool: link: g++ -I/usr/lib/x86_64-linux-gnu/include -I/include -Wall -Wno-unused-local-typedef -pedantic -ffast-math -O3 -fomit-frame-pointer -fno-strict-a
liasing -DNDEBUG -std=gnu++11 -o .libs/vw vw-main.o  -L/usr/lib/x86_64-linux-gnu -lboost_program_options -L/lib -lz -lpthread ./.libs/libvw.so ./.libs/liballr
educe.so
./.libs/libvw.so: undefined reference to `boost::program_options::to_internal(std::string const&)'
./.libs/libvw.so: undefined reference to `boost::program_options::arg'
./.libs/libvw.so: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
./.libs/libvw.so: undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool*, 
int)'
./.libs/libvw.so: undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::st
ring*, int)'
./.libs/libvw.so: undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
./.libs/libvw.so: undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
./.libs/libvw.so: undefined reference to `boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
./.libs/libvw.so: undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::string const&, std::string const&, std::
string const&, int)'
./.libs/libvw.so: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
./.libs/libvw.so: undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::alloca
tor<std::string> > const&, bool) const'
./.libs/libvw.so: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
collect2: error: ld returned 1 exit status
Makefile:556: recipe for target 'vw' failed
make[2]: *** [vw] Error 1
make[2]: Leaving directory '/home/vlad/git/vowpal_wabbit/vowpalwabbit'
Makefile:409: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/vlad/git/vowpal_wabbit/vowpalwabbit'
Makefile:517: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Initially I got segmentation fault with the default GCC 5.2.1. I switched to 4.8.5 as default but this resulted in this error. Some googling revealed that this might be due to Boost libraries which are compiled using the GCC 5.2.1

**Comment by arielf** [comment] 2015-10-28 05:17
Official build instructions are @ https://github.com/JohnLangford/vowpal_wabbit/blob/master/README.md

- Please avoid running autogen.sh on Ubuntu. Using the default Makefile should work fine.
- You will need to first install boost-dev and other prereqs (see link above)

**Comment by usptact** [comment] 2015-10-28 08:00
Thanks Ariel! I restarted from scratch and got ugly internal compiler errors!

I installed all prerequistes per that README.md

cd vowpalwabbit; make -j 4 things
make[1]: Entering directory '/home/vlad/git/vowpal_wabbit/vowpalwabbit'
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -DNDEBUG -I /usr/include  -fPIC  -c main.cc -o main.o
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -DNDEBUG -I /usr/include  -fPIC  -c hash.cc -o hash.o
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -DNDEBUG -I /usr/include  -fPIC  -c global_data.cc -o global_data.o
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -DNDEBUG -I /usr/include  -fPIC  -c io_buf.cc -o io_buf.o
<built-in>: internal compiler error: Segmentation fault
<built-in>: internal compiler error: Segmentation fault
<built-in>: internal compiler error: Segmentation fault
<built-in>: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:38: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:35: recipe for target 'io_buf.o' failed
make[1]: *** [io_buf.o] Error 1
Please submit a full bug report,
with preprocessed source if appropriate.
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:35: recipe for target 'global_data.o' failed
make[1]: *** [global_data.o] Error 1
Makefile:35: recipe for target 'hash.o' failed
make[1]: *** [hash.o] Error 1
make[1]: Leaving directory '/home/vlad/git/vowpal_wabbit/vowpalwabbit'
Makefile:93: recipe for target 'vw' failed
make: *** [vw] Error 2

**Comment by usptact** [comment] 2015-10-28 08:08
With the clang++ compiler I don't get the internal compiler error but the same linking error as in OP: undefined references to functions in Boost program_options. I am pretty sure that library is installed! The Makefile points to the right directories.

**Comment by JohnLangford** [comment] 2015-10-28 15:55
Wow.    

I don't have access to the right flavor of ubuntu.  On my machine (ubuntu 14.04) the default 'make' works, and the autoconf works as long as I do:
./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu

Your issues are probably undebuggable by us until we can get access to a system.  If you figure out how to make things work, please tell us how.

**Comment by usptact** [comment] 2015-10-28 16:43
I am not 100% sure in my hardware. My system hangs little bit too frequently than once in a blue moon. So I am bit suspicious about hardware issues.

Before upgrade to Ubuntu 15.10, I did routine VW compilations/installations and did not encounter such problems.

**Comment by mmroden** [comment] 2015-10-28 16:44
@usptact-- could you reproduce the issue in a docker or vagrant setup,
using 15.10 as a base image?  That can also help isolate differences
between your machine and a standard deploy.

**Comment by arielf** [comment] 2015-10-28 18:06
Last failure may be because original `Makefile(s)` may have been overwritten by `automake` (called by `autogen.sh`).

Suggestions:
- `git checkout Makefile */Makefile`   # get original Makefiles back, then `make clean && make`
- Get a fresh tree from github after installing all the boost-dev prereqs and only then start building

You may be trying to link with the wrong boost because you have some prior 'contaminated' binaries or paths in auto-generated Makefiles.

In order to see which boost libs you're trying to use (which is why it fails) you may try:
    `ldd ./vowpalwabbit/.libs/libvw.so`

(if you have `.libs` it is a clear indication of running `automake` and `libtool` which is the source of all the problems.)

The correct location for all boost objects is the standard place `/usr/lib/x86_64-linux-gnu`
e.g.: `/usr/lib/x86_64-linux-gnu/libboost_program_options.so`  no need for autogen/automake/libtool and non-standard paths to libs.  You may also want to verify that you don't have `LD_PRELOAD` in your env.

**Comment by JohnLangford** [comment] 2015-11-30 20:43
I'm closing this for now because there is nothing further that we can do.

**Closed by JohnLangford** 2015-11-30 20:43 UTC
