### ISSUE TITLE
Errors when lines get too big.

### ISSUE THREAD

**Issue by JannisH** [JohnLangford/vowpal_wabbit#1092] opened 2016-08-24 17:41 UTC
Hello,

I recently stumbled upon an error for which I have not found any fix. Basically I want to classify some texts with tf idf features. If training examples reach a certain line length vw however will throw "is too many tokens for a simple label" typish errors. To confirm that I didn't mess up data conversion I wrote some python script to generate random data and reproduce the error. The same thing happens there.
Code:

```
import string
import numpy as np

txt = '1 |f '
letters = string.ascii_lowercase
features = ''
feature_num = 2103
for i in range(feature_num):
    indices = np.random.randint(0,len(letters),15) 
    features +=  ''.join([letters[j] for j in indices])+':'+str(np.random.randn(1)[0])+' '

features += 'end:1.9\n'
f = open("test.txt",'w')
f.write(txt+features)

```

so if I create 2103 or more features here vw will mostly throw an warning or error and not do anything but for anything less everything works just fine. So is there a known issue for line lengths Im not aware of or is this something else?

**Comment by arielf** [comment] 2016-08-24 18:24
@JannisH 

Thanks for the report.
Sadly the information isn't enough to reproduce.
- The python script aborts with `NameError: name 'l' is not defined`
- There's no `vw` command line to run
Could you help make the problem reproducible by others?

**Comment by arielf** [comment] 2016-08-24 18:29
And if I change `l` to `letters` so the python script runs fine, I still can't reproduce any vw error or warning even if I make the line way longer (10,000 features).

**Comment by JannisH** [comment] 2016-08-24 23:49
Thank you for your help!Yes sorry I forgot to change the variable name here. Thats super strange I think I got the latest version (8.1.1 ?) do you have any idea what else I could try to solve this? Or could this be some character encoding problem?

**Comment by arielf** [comment] 2016-08-25 01:18
Latest is 8.2.1 and pushes on top of that happen frequently. Try `vw --version`

Really can't tell what the problem is, as I can't reproduce.  If you want help, you'd need to:

- Use latest code
- Post a reproducible (full details) problem description

As is, I'm afraid this issue should be closed as "Unreproducible / Works for me".

**Comment by JohnLangford** [comment] 2016-11-19 00:06
Closing this for now--can't reproduce.  @arielf, thanks for your help.

**Closed by JohnLangford** 2016-11-19 00:06 UTC
