### ISSUE TITLE
Inconsistent behaviour with cache and -b 30

### ISSUE THREAD

**Issue by mateusgm** [JohnLangford/vowpal_wabbit#1322] opened 2017-09-06 09:30 UTC
Hi there,

I'm facing an weird issue: training with cache with -b 30 give totally different results from when I train without cache (reduced features by half and greatly increased error on validation set).

The commands i'm using:

>     cat train.vw | vw -b 30 -c -f tmp/model1    (output: https://pastebin.com/raw/ttw59eDE)
>     cat train.vw | vw -b 30 -c -f tmp/model2    (output: https://pastebin.com/raw/JunYx0aM)
>     cat test.vw  | vw -i tmp/model1 -t          (output: https://pastebin.com/raw/EUsMQHqa)
>     cat test.vw  | vw -i tmp/model2 -t          (output: https://pastebin.com/raw/2TbLdXuR)

The results:

>                       training    test
>     model1 -b 30:     0.166483    0.157583
>     model2 -b 30:     0.162706    4.579413
>     model2 -b 29:     0.166483    0.157484 

If i inspect the models (-b 30) generated with --invert_hash:

>   wc -l .readable*
>       126987 .readable1
>       61121 .readable2

I'm using vw 8.0 on a x86_64 machine (uname -m)  with 24 cores and 96Gb.

Cheers,

Mateus

**Comment by JohnLangford** [comment] 2017-09-06 16:00
This should not be happening.   Can you provide a minimal example showing divergence between text & cache?

**Comment by arielf** [comment] 2017-09-07 03:00
Not an answer, but just a few observations & suggested further work:

- Cache is anonymous (filename `.cache`) because input comes via stdin and `--cache_file` isn't specified
- When cache is used, divergence starts very early (between example 4 and 8) on the exact same training command (reading from cache vs not).
- The 2 last lines (testing) in the example above look inconsistent: compare number of features in the very first example (1): 31 vs 25 features.

cache is definitely messed-up.

Is this only reproducible with `-b 30`?  Can you try `-b 29`?

More importantly: Is this reproducible with latest source?
8.0 is over 2 years old. Many bugs have been fixed since.

**Comment by mateusgm** [comment] 2017-09-08 10:13
With `-b 29` it works fine (results on original post).

Will rerun with `-b 31` to see what it looks like and also will rerun with latest vw. If the problem holds will try to find a minimal reproducible example.

**Comment by MLWave** [comment] 2017-09-16 22:46
Just another data point: When using VW 7.x I sometimes ran into this bug where `-b 30` (or any other value close to your system's memory limit) generates an empty model file (or cache file). Like shown, above, going down a (few) bit to `-b 29` solved this, without any significant performance degradation.

And for better iterations / replicability / bug avoidance it is usually a good idea to always kill the cache, because when cache gets stale, or does not match newer input data or commands, some weird bugs can pop up: `-c -k`.

**Comment by mateusgm** [comment] 2017-09-21 07:24
Short update: tried really hard to run with vw 8.2 but failed (long story short: no sudo access, C compiler without C++11, wasnt able to compile everything)

I'll try to replicate in my personal laptop and report back.

**Comment by JohnLangford** [comment] 2017-09-21 14:37
You can compile static on a different machine then copy over?

-John

**Comment by mateusgm** [comment] 2017-09-24 12:12
Didnt work =/

Tried compiling in a Mac and on a centos 7 (final box is centos 6).
The binary I got from the Mac was incompatible; on the centos, libstdc++ is still too old (doesnt have <codecvt>), so I tried with clang and libc++  but in the end libc++ is not static linked. 

I even tried with `-all-static`, but libtool screams with `libtool: link: warning: complete static linking is impossible in this configuration`

I could try upgrading libstdc++ instead, but dont have enough experience to tell if it'll make a difference, so dont want to waste time there unless I can be sure that will work.

Any idea of what else I could try?

**Comment by mateusgm** [comment] 2017-09-24 13:12
Here is what I did (in case you guys can spot any mistakes/redflags)
https://gist.github.com/mateusgm/f7a33b2061d37b5f69c285c506e525b2

All tests passes, but when copied over and executed on the other box it complains about missing shared lib

**Comment by arielf** [comment] 2017-09-24 18:31
I won't be using `libtool`.  If you use `libtool`, it means you have run `autogen.sh` which called `configure` which called `libtool` and also overwrote the original `Makefile`s due to `automake`.

Try to:

- Get your original (pristine) Makefiles back:   `git checkout Makefile */Makefile`
- Build everything statically:   `make CXX='g++ -static'`
- Test: `make test`

Now your `vowpalwabbit/vw` should be good for copying elsewhere.

A properly statically linked executable should never complain about missing libs.

And indeed you can't run a MacOS built executable on Linux (or vice versa) directly.

However, you can run a Linux/IA64 statically built executable on any version of Linux, even one that is many many years old.  I do it all the time. and it works well.

**Comment by mateusgm** [comment] 2017-09-25 08:25
Gotcha.

After recompiling some libs it works with `make clean test`, but not with the static option.

It complains when generating `vw` binary:

`g++ -static -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -o vw main.o -L. -l vw -l allreduce -L /usr/local/lib -L /usr/lib -L /usr/lib/x86_64-linux-gnu -l boost_program_options -l pthread -l z

/bin/ld: cannot find -lz`

Tried rerunning including the lib directory I get out of `ldconfig -p | grep libz`, without any success:

make CXX='g++ -static' BOOST_LIBRARY='-L /lib64/'

**Comment by mateusgm** [comment] 2017-09-25 08:38
Although I cant explain why, I recompiled libz and it worked =)
Will rerun the tests today and report back.

**Comment by mateusgm** [comment] 2017-09-25 09:11
The issue is not present on latest master.
Do you still want a replicable example or we can close the issue?
Cheers!

**Comment by JohnLangford** [comment] 2017-09-25 13:47
We should close it.

-John

**Comment by arielf** [comment] 2017-09-25 21:12
Yes, we should close, so closing (works in latest).

@mateusgm regarding `-lz` not working: you need to have `zlib` (with its headers) installed to build `vw`. I don't know what package this in in RHEL/CentOS, but on Ubuntu/Debian you can get them using: `apt install  zlib1g-dev` 

zlib1g-dev  contains, among other files, the headers:
```
 /usr/include/zlib.h
 /usr/include/zconf.h
```

Plus, both dynamic and static libs:
```
 /usr/lib/x86_64-linux-gnu/libz.so
 /usr/lib/x86_64-linux-gnu/libz.a
```

**Closed by arielf** 2017-09-25 21:12 UTC
