### ISSUE TITLE
Sequence Tagging do not output the correct number of predictions for large sequences

### ISSUE THREAD

**Issue by bratao** [JohnLangford/vowpal_wabbit#957] opened 2016-03-01 19:32 UTC
Hello, 

First of all, thank you for this awesome project. I guess this is related to @KaiWeiChang @hal3 work. Thank you !!

I want to tag a very large sequence ( more than 5000 tags in a single example) , but the output is wrong comparated to the input. 

You can simulate by taking the **wsj.wv.zip** example, and removing all the new lines, to be considered a single example.  Using the line below to train and test using the same dataset:

```
vw -b 24 -d wsj.test.vw -c --search_task sequence --search 45 -f wsj.weights
vw -d wsj.test.vw -i wsj.weights -t -p test.pred

```

The generated prediction file is this:
`1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 `

Only 42 labels, however the input is composed of 56684 labels!

**Comment by JohnLangford** [comment] 2016-03-01 23:25
Try increasing --ring_size.   VW has a limited number of examples in 
flight internally at any moment which is conflicting with very long 
sequences.

-John

**Comment by bratao** [comment] 2016-03-02 00:27
@JohnLangford , thank you for the help. 
However, I increased to '--ring_size 8096,  with no luck. The memory usage exploded, but the end result was the same.

**Comment by JohnLangford** [comment] 2016-03-05 20:13
I'm not sure what the issue is then.  @KaiWeiChang @hal3 any ideas?

**Comment by JohnLangford** [comment] 2016-03-05 20:14
One thing that would really help is finding a minimal reproducible example.  (More minimal than the wsj approach)

**Comment by KaiWeiChang** [comment] 2016-04-18 03:41
Hi Bratao, 

Sorry for the late response. Have you figured out the problem? I tried the latest version of vw, it seems that it can produce the correct number of labels now on the wsj example.  Also, could you make sure there is a linebreak in the end of file? 

Best, 
Kai-Wei

**Comment by JohnLangford** [comment] 2016-07-25 18:10
Assuming fixed, and closing.

**Closed by JohnLangford** 2016-07-25 18:10 UTC
