### ISSUE TITLE
Test 105 Error when running make test

### ISSUE THREAD

**Issue by MartinDelzant** [JohnLangford/vowpal_wabbit#872] opened 2015-12-01 16:04 UTC
Hello, 

I am new to VW and wanted to install it on my computer, so I followed the Readme file : installed the libboost package, ```make``` and ```make test```, but the test 105 failed for some reason : 
```
line 1: fuzzy-match missing data on one of the sides.
```
(I can give the complete error if it's of any interest)

I was wondering if I did something wrong or if this was a known issue ?

Thank you,

**Comment by arielf** [comment] 2015-12-04 06:35
Thanks.  I hit this too.

This seems to be a test-reference issue (test reference: `train-sets/ref/0001_ftrl_holdout.stderr` seems to be incorrect/not up-to-date).  The input has 200 lines in it, so with 10 passes and a 1:10 holdout, 1800 examples in the output seems to be correct (the reference stderr has only 500)

@JohnLangford can you confirm?  Need to push an updated reference file.

```
RunTests: test 105: lenient-diff.tmp: line 1: fuzzy-match missing data on one of the sides. Can't compare
                                                                              >0.291543 0.250866         1024         1024.0   1.0000   0.3258       94
RunTests: test 105: saving lenient diff in 'test-105.lenient-diff' for later inspection
--- diff -u --minimal train-sets/ref/0001_ftrl_holdout.stderr 0001_ftrl_holdout.stderr
--- train-sets/ref/0001_ftrl_holdout.stderr     2015-11-02 15:16:03.641656258 -0800
+++ 0001_ftrl_holdout.stderr    2015-12-03 22:23:41.972098280 -0800
@@ -24,12 +24,13 @@
 0.363809 0.407095          128          128.0   0.0000   0.1093       30
 0.344932 0.326056          256          256.0   0.0000   0.1545       72
 0.332219 0.319506          512          512.0   0.0000   0.2409       37
+0.291543 0.250866         1024         1024.0   1.0000   0.3258       94

 finished run
-number of examples = 540
-weighted example sum = 540.000000
-weighted label sum = 240.000000
-average loss = 0.000000 h
+number of examples = 1800
+weighted example sum = 1800.000000
+weighted label sum = 800.000000
+average loss = 0.246914 h
 best constant = 0.444444
 best constant's loss = 0.246914
-total feature number = 41349
+total feature number = 137830
RunTests: test 105: FAILED: ref(train-sets/ref/0001_ftrl_holdout.stderr) != stderr(0001_ftrl_holdout.stderr)
        cmd: /usr/bin/timeout 30 ../vowpalwabbit/vw -k -d train-sets/0001.dat -f models/0001_ftrl.model --passes 10 --ftrl --ftrl_alpha 0.01 --ftrl_beta 0 --l1 2 --cache
make: *** [test] Error 1
```

**Comment by arielf** [comment] 2015-12-04 06:44
Should be fixed in:  https://github.com/JohnLangford/vowpal_wabbit/pull/875

**Comment by arielf** [comment] 2015-12-04 07:27
After fixing this, the test after it (106) is failing on stderr.

Fixed this too but the predictions seem much worse than they were before so the prediction part of 106 seems to have a regression after fixing the `--ftrl` with holdout bug.

I'm reluctant to override the  `pred-sets/ref/0001_ftrl_holdout.predict` which looks more correct.

**Comment by JohnLangford** [comment] 2015-12-04 19:27
This is fixed now.  The prediction degradation is just due to early 
stopping triggering earlier than before.  (The dataset is very small, so 
this is not particularly meaningful.)

-John

**Closed** 2015-12-04 20:18 UTC
