### ISSUE TITLE
vw use -a key Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by SergeyParamoshkin** [JohnLangford/vowpal_wabbit#1038] opened 2016-07-15 09:13 UTC
Hi, I compiled with debug mode. assembly was held without any errors.
I run vw and get the error. if  use the -a option

```
stdout stream | head -1 | vw --l1 0.00001 -a
using l1 regularization = 1e-05
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile =
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0 1
Segmentation fault (core dumped)
```

```
$ gdb core.34115
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-90.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Missing separate debuginfo for the main executable file
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/d7/44476ca63cf73878669c36efbb630bb412db69
[New Thread 34115]
Core was generated by `vw --l1 0.00001 -a'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f84612c9d36 in ?? ()
"/home/svparamo/core.34115" is a core file.
Please specify an executable to debug.
(gdb) file /usr/local/bin/vw
Reading symbols from /usr/local/bin/vw...done.
(gdb) start
No core file now.
Temporary breakpoint 1 at 0x402618: file main.cc, line 66.
Starting program: /usr/local/bin/vw
[Thread debugging using libthread_db enabled]

Temporary breakpoint 1, main (argc=1, argv=0x7fffffffe4b8) at main.cc:66
66      { try
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6_7.7.x86_64 libboost_program_options1_59_0-1.59.0-1.x86_64 libgcc-4.4.7-17.el6.x86_64 libstdc++-4.4.7-17.el6.x86_64 zlib-1.2.3-29.el6.x86_64
```

env: 
rhel 6.7
gcc - gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)
boost-devel-1.59.

```
No package debuginfo-install available.
Package glibc-2.12-1.166.el6_7.7.x86_64 already installed and latest version
Package libboost_program_options1_59_0-1.59.0-1.x86_64 already installed and latest version
Package libgcc-4.4.7-17.el6.x86_64 already installed and latest version
Package libstdc++-4.4.7-17.el6.x86_64 already installed and latest version
Package zlib-1.2.3-29.el6.x86_64 already installed and latest version
```

**Comment by arielf** [comment] 2016-07-15 17:59
This is a typical thing that happens on Red-Hat: a dynamically linked `vw` executable trying to run against an incompatible version of the boost library.

Solution: build your vw statically with `make CXX=gcc -static` and these problems should go away.
Or use one of these:
[statically linked executables](http://finance.yendor.com/ML/VW/Binaries/)

**Comment by arielf** [comment] 2016-07-15 18:13
Also, for reference.  I can't reproduce this with latest:

```
$ echo "1 | a b c" | vw --l1 0.00001 -a
using l1 regularization = 1e-05
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile =
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0
        a:92594:1:0@0   b:163331:1:0@0  c:185951:1:0@0  Constant:116060:1:0@0
1.000000 1.000000            1            1.0   1.0000   0.0000        4

finished run
number of examples per pass = 1
passes used = 1
weighted example sum = 1.000000
weighted label sum = 1.000000
average loss = 1.000000
best constant = 1.000000
best constant's loss = 0.000000
total feature number = 4
```

Runs fine.

But I can't reproduce the `stdout stream` above so there's a (remote chance) this might be data-dependent. Please provide actual reproducible details.:

**Comment by arielf** [comment] 2016-07-16 16:17
Puzzle solved.

It happens when there's an empty feature name with a weight:

Example:
     4 |  :1.3

[See also PR 1041](https://github.com/JohnLangford/vowpal_wabbit/pull/1041)

**Comment by JohnLangford** [comment] 2016-08-09 19:03
This is fixed, thanks.  Closing.

**Closed by JohnLangford** 2016-08-09 19:03 UTC
