### ISSUE TITLE
LDA returns same words for every topic with 8.2.1

### ISSUE THREAD

**Issue by akmcinto** [JohnLangford/vowpal_wabbit#1119] opened 2016-10-21 22:14 UTC
I'm using LDA to compute topics.  However, using release 8.2.1 Vowpal Wabbit returns the same words for every topic.  Using the command:

`vw -d 'vr_lda_input.lda.txt' --lda 30 --lda_alpha 0.1 --lda_rho 0.1 --minibatch 256 --power_t 0.5 --initial_t 1 -b 4 --cache_file 'topics.dat.cache' --passes 2 -p 'predictions.dat' --readable_model 'topics.dat'`

where the input file (vr_lda_input.lda.txt) is a collection of word counts of filtered words. 
[vr_lda_input.lda.txt](https://github.com/JohnLangford/vowpal_wabbit/files/545302/vr_lda_input.lda.txt)

Topics are generated in topics.dat, but the values for each topic are the same. 
[topics.txt](https://github.com/JohnLangford/vowpal_wabbit/files/545340/topics.txt)

This command and dataset work with release 8.2.0, generating different values for each topic. 
[topics_using820.txt](https://github.com/JohnLangford/vowpal_wabbit/files/545339/topics_using820.txt).

**Comment by arielf** [comment] 2016-10-22 00:32
Thanks @akmcinto 

I'm not sure I can reproduce this.
I get some similar weights but not identical across topics.  There's a variability between topics.
e.g. the 1st 3 lines in the predict file (I added an empty line between them for clarity) show:
```
0.100020 0.100022 0.100017 0.100032 0.100023 0.100026 0.100025 0.100027 0.100023 0.100039 0.100029 0.100021 0.100020 0.100034 0.1$00026 0.100025 0.100022 0.100035 0.100027 0.100034 0.100021 0.100026 0.100020 0.100025 0.100023 0.100021 4.099268 0.100025 0.100023 0.100019

0.100012 0.100018 0.100022 0.100015 0.100019 0.100015 0.100030 0.100028 0.100019 0.100018 0.100020 0.100015 0.100018 0.100026 0.100019 0.100023 0.100021 0.100038 0.100021 0.100020 0.100022 0.100019 0.100012 0.100028 0.100017 0.100019 0.100020 0.100028 0.100023 4.099395

0.100014 0.100022 0.100042 0.100020 0.100028 0.100020 0.100032 0.100031 0.100016 0.100017 0.100030 0.100020 0.100029 0.100031 0.100013 0.100025 0.100031 0.100034 0.100027 0.100031 0.100035 0.100030 0.100016 0.100035 0.100015 0.100019 0.100022 0.100029 0.100027 1.099259
```

Curious: why do you use `-b 4` (weight-vector is only 16-slots, which causes a very large number of feature collisions). Does it work better if you just leave the default (`-b 18`) as is?

Thanks!

**Comment by arielf** [comment] 2016-10-23 19:47
Preliminary narrowing down of this regression, using a few older executables I have saved.

- vw-8.20160817 is ok - shows 16 distinct topics in readable model for this test case
- vw-8.20160906 has the bug (only one distinct topic)

So the regression seems to have happened in this year aug/sept time-frame.

**Comment by arielf** [comment] 2016-10-23 22:25
Working with git bisect on this case proved nearly impossible.  There are too many commits around Aug 18 (and the July/Sept time frame) that don't build (on Linux) or SEGV, so git bisect starts going way back in time and giving a long list of possible bad commits none of which is relevant (even though it was told of a [good bad] commit time range it keeps stepping out of the specified range.)

By going manually commit by commit I was able to find the last commit that actually worked correctly for this case:
      3a38eab2c7096ed546575e1d7cbcafb343544929 Aug 18 18:53:19

This somewhat later commit is the closest that failed the test and I was able to build:
     4ac60b59b930017a3aec95307c29266ec0875158 Thu Aug 18 20:37:25 BAD

The test is:  given the input file in this report: `vr_lda_input.lda.txt`, I run:
```
vw -k --lda 30 --lda_alpha 0.1 --lda_rho 0.1 --minibatch 256 --power_t 0.5 --initial_t 1 -b 4  --cache_file topics.dat.cache --passes 2 --readable_model topics.readable
```

Then I checked the readable model with this little bash script:

```
#!/bin/bash
n_topics=`sed -e '1,/Checksum:/d' -e 's/^[0-9]* //' topics.readable |sort -u |wc -l`
echo "Found $n_topics distinct topics in topics.readable"
case "$n_topics" in
    (16) exit 0
         ;;
    (*)  echo === `which vw` has the BUG '!!!'
        exit 1
        ;;
esac
```
Hopefully this could help pinpoint the change that caused the regression.

**Comment by arielf** [comment] 2016-10-24 00:25
For the sake of completeness:
`git bisect run ...` pointed at the following skipped commits as possible root causes:
```
The first bad commit could be any of:
429255f1d39c47fbd5363c54e1817ad0278c3c3f       Thu Jun 16
61c896a38d3cde2c40cecb4e56eab420d91c35b3    Thu Jun 16
3af60190aa92633b4389b053a43aa45b0f5dbcba     Thu Jun 16
439cc3796434d4cf50f5cc20246a9a60e09b0668      Thu Jun 16
45730c0896b1d943c1e059602598665ab96e3ca0   Thu Jun 16
68228e9a13aa81a3a32b7fdf3d8a55515023570e    Mon Jun 27
1ed2e7ab2bc298f6659541d466a77f7e6d8426ab    Mon Jun 27
We cannot bisect more!
```

**Comment by eisber** [comment] 2016-10-25 18:12
Not sure if this is of any help, but I’m able to get sensible topics when using a pre-trained model for prediction.

**Comment by arielf** [comment] 2016-10-26 18:40
Thanks Markus,
Yes, predictions seem to be working, it is the readable model that seems to have the bug. Maybe the issue is just when dumping regressor as readable.  In any case, this is a regression, since in the past `--readable_model` worked fine with `--lda` as well.

**Comment by JohnLangford** [comment] 2016-11-18 19:34
Thanks Ariel/Markus/akmcinto for the help.  Unfortunately, I cannot reproduce.  The topics that I get from the current master on Ubuntu 16.04 are below.  Is this problem solved?  

`Version 8.2.1
Id
Min label:0
Max label:0
bits:4
lda:30
0 ngram:
0 skip:
options: --lda 30 --lda_alpha 0.1 --lda_rho 0.1
Checksum: 495864866
0 698.424 44.0161 82.6424 28.3573 102.965 26.67 31.7477 28.2295 34.3042 27.8887 47.3447 105.097 44.3736 30.6739 45.1424 30.3847 30.2487 42.9595 63.613 27.6051 124.452 69.2358 25.5792 42.9684 77.4852 74.7755 38.4858 87.6604 33.3242 77.7763 
1 34.8298 40.8099 102.161 35.1534 53.3719 32.5561 60.9759 53.5211 29.8331 31.0424 128.463 35.9231 168.157 61.2423 25.0115 61.7385 47.4403 90.3304 63.4869 119.087 62.6083 54.8985 50.2472 83.458 25.9913 38.3673 41.6393 55.9627 82.2182 265.7 
2 65.7285 37.9751 51.8512 64.0396 38.1022 44.8228 33.0338 31.5179 26.0544 31.6977 61.8292 61.8332 143.814 31.3099 40.0047 176.745 24.7291 27.4974 63.3598 115.668 46.6715 67.9431 83.8548 26.4196 37.7172 30.6976 65.587 42.6206 161.731 28.6266 
3 182.285 35.4334 67.8389 80.6138 28.7773 51.7815 138.808 104.827 109.116 33.848 58.325 29.755 178.49 58.6331 160.287 28.3187 37.3278 37.2845 63.2303 134.425 37.1067 39.3736 51.7342 34.9302 123.354 25.8292 49.5079 34.0393 29.1437 35.3508 
4 32.9592 33.1324 397.022 170.648 79.1841 74.0796 75.7029 35.3142 62.8125 36.2075 29.4317 47.0723 26.9304 31.959 35.7581 87.4006 64.792 53.8738 63.1032 42.09 30.2523 34.2147 145.158 70.1276 28.0753 76.4834 54.6569 27.7027 39.6764 68.2686 
5 39.374 31.0305 35.4932 29.4621 48.5897 26.1535 71.0848 156.8 105.735 38.8208 48.8802 24.8357 30.8513 60.6831 86.5212 99.049 30.1987 318.816 62.978 27.4096 24.9069 29.9586 24.9334 100.805 41.1805 54.72 116.399 86.6849 88.4797 101.815 
6 102.002 29.0955 105.553 36.6222 35.4275 31.8996 35.8234 39.8155 42.5608 42.9627 26.7531 37.9405 35.5245 32.6288 32.1446 45.8531 47.3372 32.683 62.8538 95.8924 66.6949 26.3355 50.2196 28.893 187.15 43.3985 96.2144 55.6918 25.5755 306.349 
7 55.3202 27.3018 26.9551 72.8661 26.9211 39.4262 139.114 25.0019 36.4969 45.0724 68.2794 68.1849 82.6255 94.0167 157.711 36.3834 24.6877 45.5001 62.7288 52.6457 48.7128 117.281 94.835 38.5152 69.5777 35.6922 143.792 42.4625 34.3805 29.1337 
8 75.0702 27.3872 39.6279 64.5469 67.3668 50.3605 63.4146 45.3339 31.6422 49.2487 414.74 31.3069 48.8978 33.3147 34.8687 117.737 37.2588 74.1156 62.6029 101.713 38.4678 65.7982 104.638 76.6422 45.2184 29.8422 203.053 33.928 48.2837 36.0211 
9 67.5945 130.156 67.4781 24.8495 44.5923 70.6827 128.302 27.8552 27.5954 72.5992 39.4288 50.3377 59.9736 84.7076 47.9626 24.6454 64.5818 28.8106 62.4794 41.7355 31.2735 52.9254 106.088 317.377 215.344 25.1273 25.7877 27.617 126.891 45.6511 
10 108.228 86.2008 29.795 30.6175 33.0162 25.6463 38.9723 52.4783 145.295 64.0879 123.079 26.0969 122.129 34.0221 31.5008 33.7697 30.147 39.274 62.3568 47.5394 25.7236 47.1814 437.708 31.6445 52.308 77.1906 27.6119 85.7427 30.0289 113.678 
11 51.0354 71.6541 44.6092 38.183 25.1946 31.2585 220.615 31.0878 70.691 85.8912 35.7288 40.1377 25.3801 68.1226 42.261 90.8527 47.2315 57.9679 62.2343 54.1688 71.6018 38.5363 48.7561 42.7158 50.0601 72.1172 29.5832 55.4212 67.1233 401.459 
12 41.1408 62.8289 88.7166 49.2038 59.4384 38.5591 64.3254 62.6204 55.2372 77.1187 91.6405 76.7931 29.0408 34.7509 225.844 336.354 24.6463 55.336 62.1136 33.2868 50.9404 33.3506 57.025 93.4093 24.7077 42.0512 31.7286 42.3053 61.6961 50.6342 
13 105.044 58.7122 33.0107 89.451 41.1594 49.0194 24.6139 60.8858 45.6904 149.731 52.1894 32.9653 36.6338 92.3256 73.4037 31.4105 37.1915 34.3186 61.9927 290.846 39.9106 29.2302 103.119 26.2897 35.6743 35.8121 54.4057 33.8183 26.338 36.7113 
14 28.9623 52.4669 158.43 25.8041 30.8242 67.9177 66.2036 210.167 41.3825 24.7433 74.0192 54.1113 38.5826 35.5029 112.772 63.4566 64.3778 48.3342 61.8739 41.3885 32.3411 26.9214 166.62 53.8593 56.1088 29.0189 57.6743 27.5331 35.4832 70.2934 
15 55.156 74.5691 38.8938 75.2524 160.318 38.8493 39.4928 60.6061 51.9173 45.2634 45.9604 42.3724 69.9421 136.56 52.1675 189.145 46.5005 166.839 95.469 60.8515 41.0447 165.954 248.488 115.007 41.2183 370.476 61.1942 131.179 77.7022 118.558 
`

**Comment by JohnLangford** [comment] 2016-11-18 19:36
I'm closing on the theory this is solved, but please reopen if it's not with the current master.

**Closed by JohnLangford** 2016-11-18 19:36 UTC

**Comment by arielf** [comment] 2016-11-19 02:17
Thanks.
Just verified that this is, indeed, fixed in latest (top of tree)

```
# Running my regression test for this (script included above):
18:07 $ Regressions/lda-same-topic>  ./test-lda-readable ../../vowpalwabbit/vw
Found 16 distinct topics in topics.readable
=== ../../vowpalwabbit/vw is GOOD
```
