### ISSUE TITLE
Train results reporting is broken for --save_resume -f xxx without --preserve_performance_counters

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#1211] opened 2017-03-11 01:26 UTC
Hi,

This one is fine:
```
$ vowpalwabbit/vw -d test/train-sets/0001.dat -f /tmp/m  --passes 2 -c -k  -P 50

average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.235697 0.235697           50           50.0   1.0000   0.4783       21
0.220809 0.205921          100          100.0   1.0000   0.6434       41
0.210683 0.190432          150          150.0   1.0000   0.4742       38
0.182728 0.182728          200          200.0   1.0000   1.0000       88 h
0.167471 0.100341          250          250.0   0.0000   0.0920       41 h
0.175111 0.209492          300          300.0   0.0000   0.0677       14 h
0.179518 0.208603          350          350.0   0.0000   0.0000      122 h
```
Now considering training model and saving it with `--save_resume` mode. This one is broken:
```
vowpalwabbit/vw -d test/train-sets/0001.dat -f /tmp/m  --passes 2 -c -k  -P 50 --save_resume

average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.235697 0.235697           50           50.0   1.0000   0.4783       21
0.220809 0.205921          100          100.0   1.0000   0.6434       41
0.210683 0.190432          150          150.0   1.0000   0.4742       38
0.198724 0.198724            1            1.0   1.0000   1.0000       51 h
0.172289 0.066550           51           51.0   0.0000   0.2822       71 h
0.174703 0.184761          101          101.0   0.0000   0.1612       49 h
0.184914 0.248224          151          151.0   1.0000   0.9572       46 h
```

Note that example counter is reseted at the end of every pass throw dataset. And average loss since second pass is calculated incorrectly as it was zeroed too. It may be hard to notice if you're using logarithmic steps for progress reporting and big dataset. Also this seems to not affect totals.

Everything got fixed if I add `--preserve_performance_counters`.
```
$ vowpalwabbit/vw -d test/train-sets/0001.dat -f /tmp/m  --passes 2 -c -k  -P 50 --save_resume --preserve_performance_counters

average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.235697 0.235697           50           50.0   1.0000   0.4783       21
0.220809 0.205921          100          100.0   1.0000   0.6434       41
0.210683 0.190432          150          150.0   1.0000   0.4742       38
0.182728 0.182728          200          200.0   1.0000   1.0000       88 h
0.167471 0.100341          250          250.0   0.0000   0.0920       41 h
0.175111 0.209492          300          300.0   0.0000   0.0677       14 h
0.179518 0.208603          350          350.0   0.0000   0.0000      122 h
```
Apparently the execution flow somehow reaches `gd.cc::save_load_online_state()` at the end of each pass and reset all reporting variables to 0 as `--preserve_performance_counters` is false by default. 
Frankly, I was quite frustrated today with this parameter as I pulled master branch just to make sure my private fork is working in --save_resume mode in a same way as vanilla code and realized none of them behave as expected :). And it took quite time to find a new parameter as `--preserve_performance_counters` apparently isn't finalized and not documented yet. Well, such things happen when I don't keep an eye on a project for year and still think I'm able do whatever I want with most recent master branch without consequences :).

I think `--preserve_performance_counters` should be ignored or treated as true in all cases except we have both `--save_resume` and `-i your.model` in one command line  (e.g. only when reading model file which was saved with --save_resume. Don't remember if i need to pass --save_resume again while loading or model format stores this flag).

**Comment by arielf** [comment] 2017-03-11 02:29
Alex,

If/when this get this fixed, please add a test case to `RunTests` using `--save_resume` (you may use the above example with `--preserve_performance_counters` to  generate the correct reference-files.)

Things tend to break unintentionally after major changes. They main reason these regressions go unnoticed is  because there are not enough tests to cover existing correct/expected behavior.

**Comment by JohnLangford** [comment] 2017-07-17 18:02
This is fixed in the current master, thank you.

Ariel, I also added a test case.

**Closed by JohnLangford** 2017-07-17 18:02 UTC

**Comment by arielf** [comment] 2017-07-17 18:40
Cool. Thanks!
