### ISSUE TITLE
The default namespace is not included in --quadratic=::

### ISSUE THREAD

**Issue by martinpopel** [JohnLangford/vowpal_wabbit#649] opened 2015-05-25 15:24 UTC
While `echo '1 |f a b c' | vw -q :: --audit` works as expected and reports 7 features (Constant, a, b, c, a*b, a*c, b*c),  `echo '1 | a b c' | vw -q :: --audit` reports only 4 features (Constant, a, b, c).

Before merging PR #610, `echo '1 | a b c' | vw -q :: --audit` reported 13 features (as is now reported with `echo '1 |f a b c' | vw -q :: --audit --permutations`).

**Comment by arielf** [comment] 2015-05-25 19:59
Thanks for catching. Looks like some iterators over name-spaces+features need readjust/rewrite after #610.
Need a few tests for `--audit` as well.

**Comment by trufanov-nok** [comment] 2015-05-25 22:18
I'm quite surprised that 
> Before merging PR #610, echo '1 | a b c' | vw -q :: --audit reported 13 

The reason of 4 results is that in example '1 | a b c'  features belong to empty namespace (in fact it's namspace with character ' ' (space 0x20)). Which is treated as absence of any namespace. And namespace wildcard ':' doesn't include ' '. 

wildcard includes everything [between '!' and '~'](https://github.com/JohnLangford/vowpal_wabbit/blob/88bcd410103345d431bcdb5b80dc72157f84277b/vowpalwabbit/parse_args.cc#L429) except for ['|' and ':'](https://github.com/JohnLangford/vowpal_wabbit/blob/88bcd410103345d431bcdb5b80dc72157f84277b/vowpalwabbit/parse_args.cc#L63). Note: I'm referencing branch state at commit merged just before mine.  
And according to [ASCII table](https://en.wikipedia.org/wiki/ASCII#ASCII_printable_code_chart) space is just before '!'.

So old VW should generate 4 features for `echo '1 | a b c' | vw -q :: ` even if `-q ::` specified as well as current VW. Could you please check that?
If there are 4 features and 13 with `--audit` than it was a bug in old VW code which disappeared now.

The only way to interact features which are not belong to any namespace is to reassign them to some namespace: ` vw    --redefine a:=    -q aa`

**Comment by trufanov-nok** [comment] 2015-05-25 22:22
> So old VW should generate 4 features for echo '1 | a b c' | vw -q :: even if -q :: specified as well as current VW. Could you please check that?

I recall i have old VW copy. It generates 13 features. I'll take a look into it tomorrow as it's 2:30 AM here.

**Comment by trufanov-nok** [comment] 2015-05-25 22:47
And now I can see that I missed the fact that was a special case in pairs generation:
In case -q :: the pair ' ' ' [was added to the pair list](https://github.com/JohnLangford/vowpal_wabbit/blob/c3825bc50d7d6fd2c649ec4f30ab6b091080ef1f/vowpalwabbit/parse_args.cc#L441)
It looks like there were no interactions with default namespace in case only *one* namespace in pair is a wildcard: `-q x: -q :x` and even for `-q ::`. So 'x' ' and ' 'x' were never generated.
And wildcards were not supported for `--cubic` features at all.

So I'm quite confused how it should behave now. Shall I add ' ' ' case for all interactions which consists of only wildcards? Like ' ' ' ' for --cubic :::   
Or ignore it?

**Comment by martinpopel** [comment] 2015-05-25 22:59
I would not object forbidding the use of the default (empty) namespace when `--quadratic`, `--cubic` or `--interactions` is used. But if it is forbidden, VW should give an error with a clear message when it encounters empty namespace in the data. 

Personally, I don't use empty namespace and `-q ::`, but I think have seen it in some tutorials.

I agree the wildcard ":" should have the same meaning (represent the same set of namespaces) in `-q ::`, `-q :x`, `-q x:`, `--cubic xy:` etc.

**Comment by JohnLangford** [comment] 2015-05-26 13:31
Error messages for empty quadratic namespaces are iffy.  The core issue 
is that emptyness is defined only on a per-example basis while 
quadratics are defined for all examples.  It can be legitimate to have 
an empty namespace.

I'd suggest adding the default namespace whenever encountering ':'.   
This is the expected behavior by some people and it seems plausible enough.

-John

**Comment by trufanov-nok** [comment] 2015-05-26 13:48
Just to make sure: you mean replacing `char printable_start = '!'` with `char printable_start = ' ' ` so default namespace could interact not only with itself but also with other namespaces (like `-q a:`)?

**Comment by JohnLangford** [comment] 2015-05-26 14:02
Yes.

-John

**Closed** 2015-05-26 16:06 UTC
