### ISSUE TITLE
Type of weight_index is inconsistent

### ISSUE THREAD

**Issue by palmerlao** [JohnLangford/vowpal_wabbit#1401] opened 2018-02-05 18:17 UTC
In VW, `weight_index` has type `uint64_t` [1], but the hashing functions exposed to the user return `uint32_t` [2]. 

As a result, constructing an `example` yourself with `primitive_feature_space` is not consistent with the way VW parses them. If you call `export_example` on (conceptually) equivalent examples besides the way they were created, the `weight_index` fields are truncated to the lower 32 bits for the former method.

The wiki states that all indices are projected to the `bits` value that's passed at configuration time [3]. Why was `weight_index` left as type `uint64_t`?

1: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/feature_group.h#L10 
2: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/vw.h#L130
3: https://github.com/JohnLangford/vowpal_wabbit/wiki/Feature-Hashing-and-Extraction#why-hash

**Comment by JohnLangford** [comment] 2018-03-21 14:16
The weight_index in vw used to be a uint32_t.  As RAM expanded, this eventually became obsolete so it was upgraded to 64 bits, but the interface was not (an oversight).  I'm fixing this in #1431  Upgrading to 64 bit should be backwards compatible with 32 bit-expecting code.

If you have a simple test example exercising the issue, we should probably add that to the standardized build tests.

**Comment by JohnLangford** [comment] 2018-03-21 18:37
I'm closing this as fixed, but a pull request with a test exhibiting the issue is welcome.

**Closed by JohnLangford** 2018-03-21 18:37 UTC
