### ISSUE TITLE
Sporadic protocol errors with VW LDA daemon mode

### ISSUE THREAD

**Issue by marko-asplund** [JohnLangford/vowpal_wabbit#778] opened 2015-09-09 06:53 UTC
I'm getting sporadic errors when running VW LDA in daemon mode and requesting predictions over TCP. VW is started using the following command:

```$VW -i $VW_ROOT/data/predictor.vw -t --daemon --lda_epsilon 100000 --pid_file $PID_FILE```

Occasionally VW stops responding to prediction requests and I get error messages also when trying to shut down VW. Here's an example session:

```
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
marko@zap:~/vw/5cb7389b4b$
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
calling accept
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 2.099995 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
marko@zap:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
reading data from port 26542
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
calling accept

marko@zap:~/vw/5cb7389b4b$ kill -TERM `cat vw.pid`

finished run
marko@zap:~/vw/5cb7389b4b$ number of examples = 86218
weighted example sum = 86218
weighted label sum = 0
average loss = 13.471
total feature number = 237351
vw (parser.cc:vw (553): parser.ccaccepterrno = unknown:
553): accepterrno = unknown
vw (parser.cc:553): accepterrno = unknown
vw (parser.cc:553): accepterrno = unknown
vw (parser.cc:553): accepterrno = unknown
vw (parser.cc:553): accepterrno = unknown
vw (parser.cc:553): accepterrno = unknown
vw (parser.cc:553): accepterrno = unknown
vw (parser.cc:553): accepterrno = unknown
```

This occurs with VW 5cb7389b4b on Ubuntu 13.10 (3.11.0-15-generic [x64]).

**Comment by marko-asplund** [comment] 2015-09-09 07:09
Also, when running a simple script requesting predictions in a loop using 4 concurrently running sessions and after a total number of about 20-40 k requests VW issues empty responses.

The script can be found here:
https://gist.github.com/marko-asplund/aa7883dbbbc1a8be1580

**Comment by JohnLangford** [comment] 2015-09-09 15:15
This looks unpleasant.  Why is accept returning an error?

https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parser.cc#L553

If you can investigate what the error is that might be illuminating.  
One thing that I've noticed is that 'nc' does not hold a connection open 
for a response on some platforms.

-John

**Comment by marko-asplund** [comment] 2015-09-10 12:17
I'm seeing similar errors also with our app that connects to the VW daemon over TCP. The app uses persistent VW connections. To reflect this use case I updated the Gist above to also include a short Python script that issues repeated prediction requests to VW daemon using persistent TCP connections.

When I run the Python script simultaneously in ~4-5 sessions for a while, then at the same time do a couple of requests e.g. using `nc`, VW daemon eventually seems to start giving empty responses to prediction requests on new connections (while responses from the persistent connections may still be ok).

Can I get LDA predictions using some other method? Our software runs on the JVM, but the VW JNI interface doesn't currently seem to include support for getting LDA topic vector predictions.

How widely is VW used in daemon mode?

Are you able to reproduce this issue using the scripts I provided?
I'll also try to investigate this further.

**Comment by JohnLangford** [comment] 2015-09-10 17:42
Any chance this is running on a mac? I know daemon() calls were deprecated in OS X. You'll see the deprecation warning when building.
regardsSharat 


     On Wednesday, September 9, 2015 11:16 AM, "John Langford jl@hunch.net [vowpal_wabbit]" <vowpal_wabbit@yahoogroups.com> wrote:
   

     This looks unpleasant. Why is accept returning an error?

https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parser.cc#L553

If you can investigate what the error is that might be illuminating. 
One thing that I've noticed is that 'nc' does not hold a connection open 
for a response on some platforms.

-John

On 09/09/2015 02:53 AM, marko asplund wrote:
>
> I'm getting sporadic errors when running VW LDA in daemon mode and 
> requesting predictions over TCP. VW is started using the following 
> command:
>
> |$VW -i $VW_ROOT/data/predictor.vw -t --daemon --lda_epsilon 100000 
> --pid_file $PID_FILE|
>
> Occasionally VW stops responding to prediction requests and I get 
> error messages also when trying to shut down VW. Here's an example 
> session:
>
> |marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> marko@crash:~/vw/5cb7389b4b$
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> calling accept
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 2.099995 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000 0.100000
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> marko@crash:~/vw/5cb7389b4b$ echo '| 140:2' | nc localhost 26542
> reading data from port 26542
> average since example example current current current
> loss last counter weight label predict features
> calling accept
>
> marko@crash:~/vw/5cb7389b4b$ kill -TERM `cat vw.pid`
>
> finished run
> marko@crash:~/vw/5cb7389b4b$ number of examples = 86218
> weighted example sum = 86218
> weighted label sum = 0
> average loss = 13.471
> total feature number = 237351
> vw (parser.cc:vw (553): parser.ccaccepterrno = unknown:
> 553): accepterrno = unknown
> vw (parser.cc:553): accepterrno = unknown
> vw (parser.cc:553): accepterrno = unknown
> vw (parser.cc:553): accepterrno = unknown
> vw (parser.cc:553): accepterrno = unknown
> vw (parser.cc:553): accepterrno = unknown
> vw (parser.cc:553): accepterrno = unknown
> vw (parser.cc:553): accepterrno = unknown
> |
>
> This occurs with VW 5cb7389 
> <https://github.com/JohnLangford/vowpal_wabbit/commit/5cb7389b4b8c0a1d90582e8433425537a4a8a712> 
> on Ubuntu 13.10 (3.11.0-15-generic [x64]).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JohnLangford/vowpal_wabbit/issues/778>.
>

  __._,_.___     Posted by: John Langford <jl@hunch.net>     
|  Reply via web post  | • |   Reply to sender   | • |   Reply to group   | • |  Start a New Topic  | • |  Messages in this topic (1)  |

  Visit Your Group    
   -  New Members 2 
    • Privacy • Unsubscribe • Terms of Use 
     .  
 __,_._,___#yiv1260454067 #yiv1260454067 -- #yiv1260454067ygrp-mkp {border:1px solid #d8d8d8;font-family:Arial;margin:10px 0;padding:0 10px;}#yiv1260454067 #yiv1260454067ygrp-mkp hr {border:1px solid #d8d8d8;}#yiv1260454067 #yiv1260454067ygrp-mkp #yiv1260454067hd {color:#628c2a;font-size:85%;font-weight:700;line-height:122%;margin:10px 0;}#yiv1260454067 #yiv1260454067ygrp-mkp #yiv1260454067ads {margin-bottom:10px;}#yiv1260454067 #yiv1260454067ygrp-mkp .yiv1260454067ad {padding:0 0;}#yiv1260454067 #yiv1260454067ygrp-mkp .yiv1260454067ad p {margin:0;}#yiv1260454067 #yiv1260454067ygrp-mkp .yiv1260454067ad a {color:#0000ff;text-decoration:none;}#yiv1260454067 #yiv1260454067ygrp-sponsor #yiv1260454067ygrp-lc {font-family:Arial;}#yiv1260454067 #yiv1260454067ygrp-sponsor #yiv1260454067ygrp-lc #yiv1260454067hd {margin:10px 0px;font-weight:700;font-size:78%;line-height:122%;}#yiv1260454067 #yiv1260454067ygrp-sponsor #yiv1260454067ygrp-lc .yiv1260454067ad {margin-bottom:10px;padding:0 0;}#yiv1260454067 #yiv1260454067actions {font-family:Verdana;font-size:11px;padding:10px 0;}#yiv1260454067 #yiv1260454067activity {background-color:#e0ecee;float:left;font-family:Verdana;font-size:10px;padding:10px;}#yiv1260454067 #yiv1260454067activity span {font-weight:700;}#yiv1260454067 #yiv1260454067activity span:first-child {text-transform:uppercase;}#yiv1260454067 #yiv1260454067activity span a {color:#5085b6;text-decoration:none;}#yiv1260454067 #yiv1260454067activity span span {color:#ff7900;}#yiv1260454067 #yiv1260454067activity span .yiv1260454067underline {text-decoration:underline;}#yiv1260454067 .yiv1260454067attach {clear:both;display:table;font-family:Arial;font-size:12px;padding:10px 0;width:400px;}#yiv1260454067 .yiv1260454067attach div a {text-decoration:none;}#yiv1260454067 .yiv1260454067attach img {border:none;padding-right:5px;}#yiv1260454067 .yiv1260454067attach label {display:block;margin-bottom:5px;}#yiv1260454067 .yiv1260454067attach label a {text-decoration:none;}#yiv1260454067 blockquote {margin:0 0 0 4px;}#yiv1260454067 .yiv1260454067bold {font-family:Arial;font-size:13px;font-weight:700;}#yiv1260454067 .yiv1260454067bold a {text-decoration:none;}#yiv1260454067 dd.yiv1260454067last p a {font-family:Verdana;font-weight:700;}#yiv1260454067 dd.yiv1260454067last p span {margin-right:10px;font-family:Verdana;font-weight:700;}#yiv1260454067 dd.yiv1260454067last p span.yiv1260454067yshortcuts {margin-right:0;}#yiv1260454067 div.yiv1260454067attach-table div div a {text-decoration:none;}#yiv1260454067 div.yiv1260454067attach-table {width:400px;}#yiv1260454067 div.yiv1260454067file-title a, #yiv1260454067 div.yiv1260454067file-title a:active, #yiv1260454067 div.yiv1260454067file-title a:hover, #yiv1260454067 div.yiv1260454067file-title a:visited {text-decoration:none;}#yiv1260454067 div.yiv1260454067photo-title a, #yiv1260454067 div.yiv1260454067photo-title a:active, #yiv1260454067 div.yiv1260454067photo-title a:hover, #yiv1260454067 div.yiv1260454067photo-title a:visited {text-decoration:none;}#yiv1260454067 div#yiv1260454067ygrp-mlmsg #yiv1260454067ygrp-msg p a span.yiv1260454067yshortcuts {font-family:Verdana;font-size:10px;font-weight:normal;}#yiv1260454067 .yiv1260454067green {color:#628c2a;}#yiv1260454067 .yiv1260454067MsoNormal {margin:0 0 0 0;}#yiv1260454067 o {font-size:0;}#yiv1260454067 #yiv1260454067photos div {float:left;width:72px;}#yiv1260454067 #yiv1260454067photos div div {border:1px solid #666666;height:62px;overflow:hidden;width:62px;}#yiv1260454067 #yiv1260454067photos div label {color:#666666;font-size:10px;overflow:hidden;text-align:center;white-space:nowrap;width:64px;}#yiv1260454067 #yiv1260454067reco-category {font-size:77%;}#yiv1260454067 #yiv1260454067reco-desc {font-size:77%;}#yiv1260454067 .yiv1260454067replbq {margin:4px;}#yiv1260454067 #yiv1260454067ygrp-actbar div a:first-child {margin-right:2px;padding-right:5px;}#yiv1260454067 #yiv1260454067ygrp-mlmsg {font-size:13px;font-family:Arial, helvetica, clean, sans-serif;}#yiv1260454067 #yiv1260454067ygrp-mlmsg table {font-size:inherit;font:100%;}#yiv1260454067 #yiv1260454067ygrp-mlmsg select, #yiv1260454067 input, #yiv1260454067 textarea {font:99% Arial, Helvetica, clean, sans-serif;}#yiv1260454067 #yiv1260454067ygrp-mlmsg pre, #yiv1260454067 code {font:115% monospace;}#yiv1260454067 #yiv1260454067ygrp-mlmsg * {line-height:1.22em;}#yiv1260454067 #yiv1260454067ygrp-mlmsg #yiv1260454067logo {padding-bottom:10px;}#yiv1260454067 #yiv1260454067ygrp-msg p a {font-family:Verdana;}#yiv1260454067 #yiv1260454067ygrp-msg p#yiv1260454067attach-count span {color:#1E66AE;font-weight:700;}#yiv1260454067 #yiv1260454067ygrp-reco #yiv1260454067reco-head {color:#ff7900;font-weight:700;}#yiv1260454067 #yiv1260454067ygrp-reco {margin-bottom:20px;padding:0px;}#yiv1260454067 #yiv1260454067ygrp-sponsor #yiv1260454067ov li a {font-size:130%;text-decoration:none;}#yiv1260454067 #yiv1260454067ygrp-sponsor #yiv1260454067ov li {font-size:77%;list-style-type:square;padding:6px 0;}#yiv1260454067 #yiv1260454067ygrp-sponsor #yiv1260454067ov ul {margin:0;padding:0 0 0 8px;}#yiv1260454067 #yiv1260454067ygrp-text {font-family:Georgia;}#yiv1260454067 #yiv1260454067ygrp-text p {margin:0 0 1em 0;}#yiv1260454067 #yiv1260454067ygrp-text tt {font-size:120%;}#yiv1260454067 #yiv1260454067ygrp-vital ul li:last-child {border-right:none !important;}#yiv1260454067

**Comment by marko-asplund** [comment] 2015-09-10 18:02
This occurs with VW 5cb7389 on Ubuntu 13.10 (3.11.0-15-generic [x64]).

**Comment by JohnLangford** [comment] 2015-09-12 16:15
I played with the gist, but I don't understand it.  Why is "$siz" -lt 
"100" supposed to be an error?  Is the gist incomplete?

-John

**Comment by marko-asplund** [comment] 2015-09-12 19:00
That reflects my data set. In my case the normal response length is about 900 bytes, but in error cases the response length is 0 bytes. So, the condition might better be expressed as

```
if [ "$siz" -lt "1" ]; then
```

similar to the Python version (`vw-stress-daemon.py`).

**Comment by JohnLangford** [comment] 2015-09-12 21:59
I need something reproducible to debug.

-John

**Comment by arielf** [comment] 2015-09-12 23:08
The python stress-test script looks ok.

In order to reproduce we need a way to reproduce the daemon side as well, that means the data set and the exact command line used to create the LDA model ($VW_ROOT/data/predictor.vw above).  Can this (or a reduced data-set demostrating the issue) be provided?

I have used vw in daemon mode in production under high load successfully, but not in LDA mode.  The only issue I recall experiencing was the need to run much more than the (default) 10 children processes.

**Comment by trufanov-nok** [comment] 2015-09-16 20:13
Hi Marko,
I'm surprised with reference to https://github.com/JohnLangford/vowpal_wabbit/commit/5cb7389b4b8c0a1d90582e8433425537a4a8a712 
I'm not familiar with LDA, but expecting that this code shouldn't be even executed. Could you doublecheck that the problem isn't in earlier versions?

**Comment by marko-asplund** [comment] 2015-09-17 10:26
I built vw on a fresh test VM with debugging symbols by uncommenting the following line in the Makefile:

```FLAGS = -std=c++0x $(CFLAGS) $(LDFLAGS) $(ARCH) $(WARN_FLAGS) -D_FILE_OFFSET_BITS=64 $(BOOST_INCLUDE) -g -O0  -fPIC```

Then I re-ran the test and managed to get a core dump.

Reading the core file with gdb I get the following output:

```
masplund@foo:~/vw$ gdb /home/masplund/opt/vw/5cb7389b4b/bin/vw core1
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/masplund/opt/vw/5cb7389b4b/bin/vw...done.
[New LWP 20611]
[New LWP 20658]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/masplund/opt/vw/5cb7389b4b/bin/vw -i /home/masplund/vw/5cb7389b4b/data/pr'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000486445 in learn_batch (l=...) at lda_core.cc:757
757             l.decay_levels.end[-2] - l.decay_levels.end[(int)(-1 - l.example_t + weights_for_w[l.all->lda])];
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
(gdb)
```

**Comment by arielf** [comment] 2015-12-04 08:59
Hi Marko,

The code has changed significantly since lda_core.cc:757 had this:
```
757             l.decay_levels.end[-2] - l.decay_levels.end[(int)(-1 - l.example_t + weights_for_w[l.all->lda])];
```


This is now lines 731-732:
```
    float decay_component =
      l.decay_levels.end[-2] - l.decay_levels.end[(int)(-1 - l.example_t + weights_for_w[l.all->lda])];
```

It could help if:
1) you build with -g (debugging) and no optimizations
2) Can it still be reproduced? rerun till you get the core dump
3) run: gdb /path/to/vw /path/to/the-core-dump
4) print all the variables in the expression to try and figure out which one is causing the SEGV

I don't understand the negative indexes and this complex code.

**Comment by JohnLangford** [comment] 2016-07-25 17:52
This issue is old so I'm unsure of status.  Closing for now.  Reopen if it's still live.

**Closed by JohnLangford** 2016-07-25 17:52 UTC
