### ISSUE TITLE
"error, failed to write example" problem - c# wrapper

### ISSUE THREAD

**Issue by Wirack** [JohnLangford/vowpal_wabbit#980] opened 2016-04-20 13:03 UTC
I am utilising the c# vowpal wabbit wrapper version 8.0.0.46.

I have 90 instances of vowpal wabbit running, each of which has its own assigned cachefile name (replace X in line below with the specific instance number.)

" --cache_file mycachefilenameX.cache  --oaa 7 --loss_function logistic --sgd --passes 150"

With these amount of vowpal wabbit intances running I have experienced the following error:

> error, failed to write example

 which I have located to: [io_buf.h](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/io_buf.h) line 186

That is, it seems like a problem related to the flushing of the caches.
In cases where caches (and thus passes) are not used, I do not receive the error.
I also do not receive the error if I have a much lower amount of instances (I tried with 9 instances)

I do, however, have no idea if this is an error on my part or from vowpal wabbit.

**Comment by eisber** [comment] 2016-04-20 14:23
This might be related to https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/io_buf.cc#L103

We had some discussion on how to fix that, but haven’t come to an agreement. My proposal was to switch to boost io. I believe it’s not save to use io_buf with more than 32 instances in the same process on Windows. The errors I experienced were spurious.
Out of curiosity, how do you pass example data into VW? Strings, JSON or C# objects?

Markus

**Comment by Wirack** [comment] 2016-04-20 14:32
Thanks for the reply. That is certainly worth looking into.
As far as passing example data into VW, I currently pass it as strings, but have also tried C# Objects with the same error.

**Comment by eisber** [comment] 2016-04-20 14:52
Oh sorry for the confusion. The question on passing example data in is completely unrelated to you cache file issue.

**Comment by Wirack** [comment] 2016-04-21 13:18
Thanks, so your suggestion would be to switch from using io_buf.h to boost io, and then recompile vowpal wabbit, such that it is adjusted to those changes?

Also, is it an issue you are discussing how to handle at this point in time?

**Comment by JohnLangford** [comment] 2016-04-27 19:22
If I recall right, the problem is that windows only supports a 
relatively limited set of file descriptors.   Can you reproduce the bug 
with 33 processes but not 32?

Boost IO work is not presently happening (too busy with other stuff).  
There is almost certainly an easier fix to this problem related to more 
explicitly representing things?

-John

**Comment by Wirack** [comment] 2016-04-29 08:07
Hi.
Yes that idd seems to be the limit. I just tested and reprocuded the bug with 33 processes but not with 32 processes.

**Comment by Sunshunzhong** [comment] 2016-05-17 16:47
how could i add my code into this machine learning system?or get my source project into the system?

**Comment by JohnLangford** [comment] 2016-05-17 22:29
Send a pull request.

-John

**Comment by JohnLangford** [comment] 2016-08-09 19:12
Closing for now.

**Closed by JohnLangford** 2016-08-09 19:12 UTC
