### ISSUE TITLE
"vw: option '--bit_precision' cannot be specified more than once" error

### ISSUE THREAD

**Issue by cswhjiang** [JohnLangford/vowpal_wabbit#796] opened 2015-09-20 15:53 UTC
It seems that there is a bug in the parsing arguments section. When I run vw with````mapscript-yarn.sh```` on a cluster, I found following error from log
````
vw: option '--bit_precision' cannot be specified more than once
````

I modified  ````runvw-yarn.sh```` and changed  ````bfgscmd="./vw -b 20```` to ````bfgscmd="./vw --bit_precision 20````. It worked for now.

**Comment by JohnLangford** [comment] 2015-09-20 16:31
I don't follow what's going on here. -b and --bit_precision should be 
_precisely_ the same since they are defined on the same line here:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_args.cc#L399

Can you reproduce without using hadoop?

-John

**Comment by cswhjiang** [comment] 2015-09-20 17:02
I can reproduce it with the latest source code on hadoop. But I did not reproduce it without hadoop. I am not that familiar with VW. Here are first hundreds of lines of the error messages with "-b 20" in runvw-yarn.sh.

It seems that the problem was caused by command ````./vw -b 20 --total 9 --node 000001 --unique_id 222 --cache_file temp.cache --bfgs --mem 5 --passes 2 --save_per_pass --readable_model bfgs.rmodel --span_server my-host-name.edu -f bfgs.vwmodel -i sgd.vwmodel --loss_function=logistic ````

I can run testing command for you if you want. Thanks.


````
Container: container_1442602747157_0111_01_000014 on host-name2.edu_8041
================================================================================
LogType:stderr
Log Upload Time:Sun Sep 20 10:27:13 -0600 2015
LogLength:3177
Log Contents:
=============message================
9
my-host-name.edu
000001
9
hdfs://my-host-name.edu:8020/user/hdfs/rcv1_binary/output1
my-host-name.edu
====================== Starting training ================
======>
./vw -b 20 --total 9 --node 000001 --unique_id 0111 --passes 2 --save_per_pass --readable_model sgd.rmodel -d /dev/stdin -f sgd.vwmodel --cache_file temp.cache --span_server my-host-name.edu --loss_function=logistic 
==== 1 ====
final_regressor = sgd.vwmodel
Num weight bits = 20
learning rate = 0.5
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
==== 2 ====
creating cache_file = temp.cache
Reading datafile = /dev/stdin
num sources = 1
==== parse done ====
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.693147 0.693147            1            1.0  -1.0000   0.0000       47
0.650522 0.607896            2            2.0  -1.0000  -0.1785       83
0.498828 0.347135            4            4.0  -1.0000  -0.8751      144
0.411843 0.324858            8            8.0  -1.0000  -1.0329      120
0.289837 0.167832           16           16.0  -1.0000  -2.8559      117
0.221246 0.152654           32           32.0  -1.0000  -2.9462       59
0.162265 0.103284           64           64.0  -1.0000  -5.1873      178
0.294950 0.427635          128          128.0  -1.0000  -1.8781      135
0.337148 0.379346          256          256.0  -1.0000  -2.8606      192
0.294122 0.251096          512          512.0  -1.0000  -1.9938      104
0.313531 0.332940         1024         1024.0  -1.0000   0.6772       69
0.279840 0.246150         2048         2048.0   1.0000   1.4125       34
0.240018 0.200196         4096         4096.0  -1.0000  -3.0796       51
0.198883 0.157749         8192         8192.0   1.0000   1.9145      154
0.172253 0.145623        16384        16384.0  -1.0000  -1.5474       47
0.143826 0.115400        32768        32768.0  -1.0000  -7.4221      197
connecting to 129.107.119.9 = my-host-name.edu:26543
wrote unique_id=111
wrote total=9
wrote node=1
read ok=1
read kid_count=0
read parent_ip=129.107.119.156
read parent_port=45159
connecting to 129.107.119.156 = host-name3.edu:26544
0.126557 0.126557        65536        65536.0  -1.0000  -1.4274       64 h
Net time taken by process = 6.266000 seconds

finished run
number of examples per pass = 609662
passes used = 2
weighted example sum = 1219324.000000
weighted label sum = 60640.000000
average loss = 0.795471 h
best constant = 0.099547
best constant's loss = 0.691910
total feature number = 90431656
======>
./vw -b 20 --total 9 --node 000001 --unique_id 222 --cache_file temp.cache --bfgs --mem 5 --passes 2 --save_per_pass --readable_model bfgs.rmodel --span_server my-host-name.edu -f bfgs.vwmodel -i sgd.vwmodel --loss_function=logistic 
==== 1 ====
vw: option '--bit_precision' cannot be specified more than once
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.impl.MetricsSystemImpl).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

LogType:stdout
Log Upload Time:Sun Sep 20 10:27:13 -0600 2015
LogLength:0
Log Contents:

LogType:syslog
Log Upload Time:Sun Sep 20 10:27:13 -0600 2015
LogLength:6808
Log Contents:
2015-09-20 10:26:01,035 INFO [main] org.apache.hadoop.metrics2.impl.MetricsConfig: loaded properties from hadoop-metrics2.properties
2015-09-20 10:26:01,107 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Scheduled snapshot period at 10 second(s).
2015-09-20 10:26:01,107 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: MapTask metrics system started
2015-09-20 10:26:01,118 INFO [main] org.apache.hadoop.mapred.YarnChild: Executing with tokens:
2015-09-20 10:26:01,118 INFO [main] org.apache.hadoop.mapred.YarnChild: Kind: mapreduce.job, Service: job_1442602747157_0111, Ident: (org.apache.hadoop.mapreduce.security.token.JobTokenIdentifier@6295d394)
2015-09-20 10:26:01,168 INFO [main] org.apache.hadoop.mapred.YarnChild: Sleeping for 0ms before retrying again. Got null now.
2015-09-20 10:26:01,364 INFO [main] org.apache.hadoop.mapred.YarnChild: mapreduce.cluster.local.dir for child: /yarn/nm/usercache/hdfs/appcache/application_1442602747157_0111
2015-09-20 10:26:01,571 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: session.id is deprecated. Instead, use dfs.metrics.session-id
2015-09-20 10:26:01,926 INFO [main] org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter: File Output Committer Algorithm version is 1
2015-09-20 10:26:01,937 INFO [main] org.apache.hadoop.mapred.Task:  Using ResourceCalculatorProcessTree : [ ]
2015-09-20 10:26:02,119 INFO [main] org.apache.hadoop.mapred.MapTask: Processing split: hdfs://my-host-name.edu:8020/user/hdfs/rcv1_binary/rcv1_test.binary.vw:0+134217728
2015-09-20 10:26:02,146 INFO [main] org.apache.hadoop.mapred.MapTask: numReduceTasks: 0
2015-09-20 10:26:02,209 INFO [main] org.apache.hadoop.streaming.PipeMapRed: PipeMapRed exec [/yarn/nm/usercache/hdfs/appcache/application_1442602747157_0111/container_1442602747157_0111_01_000014/./runvw-yarn.sh]
2015-09-20 10:26:02,216 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.work.output.dir is deprecated. Instead, use mapreduce.task.output.dir
2015-09-20 10:26:02,217 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: map.input.start is deprecated. Instead, use mapreduce.map.input.start
2015-09-20 10:26:02,217 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: job.local.dir is deprecated. Instead, use mapreduce.job.local.dir
2015-09-20 10:26:02,217 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
2015-09-20 10:26:02,218 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
2015-09-20 10:26:02,219 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
2015-09-20 10:26:02,219 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.local.dir is deprecated. Instead, use mapreduce.cluster.local.dir
2015-09-20 10:26:02,219 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: map.input.file is deprecated. Instead, use mapreduce.map.input.file
2015-09-20 10:26:02,220 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.skip.on is deprecated. Instead, use mapreduce.job.skiprecords
2015-09-20 10:26:02,220 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: map.input.length is deprecated. Instead, use mapreduce.map.input.length
2015-09-20 10:26:02,221 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.cache.localFiles is deprecated. Instead, use mapreduce.job.cache.local.files
2015-09-20 10:26:02,221 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
2015-09-20 10:26:02,222 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
2015-09-20 10:26:02,237 INFO [main] org.apache.hadoop.streaming.PipeMapRed: R/W/S=1/0/0 in:NA [rec/s] out:NA [rec/s]
2015-09-20 10:26:02,238 INFO [main] org.apache.hadoop.streaming.PipeMapRed: R/W/S=10/0/0 in:NA [rec/s] out:NA [rec/s]
2015-09-20 10:26:02,248 INFO [Thread-13] org.apache.hadoop.streaming.PipeMapRed: Records R/W=72/1
2015-09-20 10:26:02,255 INFO [main] org.apache.hadoop.streaming.PipeMapRed: R/W/S=100/1/0 in:NA [rec/s] out:NA [rec/s]
2015-09-20 10:26:02,277 INFO [main] org.apache.hadoop.streaming.PipeMapRed: R/W/S=1000/1/0 in:NA [rec/s] out:NA [rec/s]
2015-09-20 10:26:02,443 INFO [main] org.apache.hadoop.streaming.PipeMapRed: R/W/S=10000/1/0 in:NA [rec/s] out:NA [rec/s]
2015-09-20 10:26:08,554 INFO [Thread-14] org.apache.hadoop.streaming.PipeMapRed: MRErrorThread done
2015-09-20 10:26:08,554 INFO [main] org.apache.hadoop.streaming.PipeMapRed: PipeMapRed failed!
java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
2015-09-20 10:26:08,642 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

2015-09-20 10:26:08,647 INFO [main] org.apache.hadoop.mapred.Task: Runnning cleanup for the task
````

**Comment by JohnLangford** [comment] 2015-09-20 17:05
Yes, can you just remove '-b 20' from the bfgs commandline?

-John

**Comment by cswhjiang** [comment] 2015-09-20 17:08
The task completed successfully.

**Comment by arielf** [comment] 2015-09-20 19:02
The problem is in mixing getting `vw` parameters (ie `-b 20`) from both the command line and from a previous `-i model` at load time.

It would be cool if the "cannot be specified more than once" error would apply only to the case where the two clashing params have a _different_ value.

Is this hard to do?

**Comment by JohnLangford** [comment] 2015-09-21 20:51
I tweaked the script to get rid of the double specification.

W.r.t. checking for double specification of the same argument... I'm not 
sure.  Boost program_options is not setup to do this, so it requires 
some unclear amount of hackery.

-John

**Comment by JohnLangford** [comment] 2015-10-19 18:32
Closing this for now.

**Closed by JohnLangford** 2015-10-19 18:32 UTC
