### ISSUE TITLE
Getting error in vw-hypersearch

### ISSUE THREAD

**Issue by pronojitsaha** [JohnLangford/vowpal_wabbit#508] opened 2015-02-04 18:58 UTC
I am using the following command:
vw-hypersearch 0.0 100 vw -b 25 --loss_function logistic --learning_rate % train.vw

I get the error ```command: vw: must start with an executable```. Now I have checked the source code and this error is generated by the following piece of code:
```
    usage("command: $ARGV[0]: must start with an executable")
        unless (-x $ARGV[0] || -x (fullpath($ARGV[0])));
```
In my case, $ARGV[0] is 0.0, so I dont understand why first of all $ARGV[0] is being taken as 'vw' and then prompting the error.

**Comment by pramitchoudhary** [comment] 2015-02-05 00:55
Hi pronojitsaha,
    The problem is not in the code but the way one is trying to execute the
binary file 'vw'. To start with, what kind of OS are you using. Is it OSX,
linux or windows. I am guess its either Linux or OSX bcauz in Windows
executables are auto generate post compilation.

Will it be possible for you to answer the following questions?
1. Are you able to execute 'vw  --help' ?
2. If not, then can you try adding permissions to make vw an executable
file and then try. I am guessing you have taken care of required path being
added to system 'Path'
for e.g. on a linux/OSX one would do something like 'chmod a+x
/usr/local/bin/vw'

Regards,
Pramit

On Wed, Feb 4, 2015 at 10:58 AM, pronojitsaha <notifications@github.com>
wrote:

> I am using the following command:
> vw-hypersearch 0.0 100 vw -b 25 --loss_function logistic --learning_rate %
> train.vw
>
> I get the error command: vw: must start with an executable. Now I have
> checked the source code and this error is generated by the following piece
> of code:
>
>     usage("command: $ARGV[0]: must start with an executable")
>         unless (-x $ARGV[0] || -x (fullpath($ARGV[0])));
>
> In my case, $ARGV[0] is 0.0, so I dont understand why first of all
> $ARGV[0] is being taken as 'vw' and then prompting the error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JohnLangford/vowpal_wabbit/issues/508>.
>



-- 
Pramit Choudhary
949.864.9717
www.linkedin.com/in/pramitc/

**Comment by pronojitsaha** [comment] 2015-02-05 07:28
Hi @pramitchoudhary, thanks for the response. I am on OSX Mountain Lion. 
1. Yes I am able to execute vw --help. My vw has permissions of an executable file, and I am able to use vw. 
2. My bash already includes alias for the path to vw and vw-hypersearch. Simply typing vw-hypersearch gives me a list of options to use. 

The problem is in the vw-hypersearch command. Even if I give the command ```vw-hypersearch 0.0 100 --loss_function logistic --learning_rate % train.vw``` it will give error ```command: --loss_function: must start with an executable```. So I guess it is taking what ever we write after '100' as the $ARGV[0] wheres $ARGV[0] should be 0.0.

**Comment by pramitchoudhary** [comment] 2015-02-05 07:33
Will it be possible to try with the full path to vw(absolute or symbolic).?

**Comment by arielf** [comment] 2015-02-05 08:48
The invocation is incorrect.  See the usage message.

You need to pass `vw` after the bound-args and before `--loss_function`:
```
vw-hypersearch 0.0 100 vw --loss_function logistic --learning_rate % train.vw
```

Also make you you set your `PATH` correctly to include the directory where `vw` is installed.

**Comment by pronojitsaha** [comment] 2015-02-05 16:47
@pramitchoudhary Using full path to vw did not work!

@arielf Thanks for the 'back to school' primer on alias and path! I changed the alias to path and now the command runs!

**Comment by pramitchoudhary** [comment] 2015-02-10 01:17
I think we can close this issue right ?

**Closed** 2015-02-10 03:02 UTC
