### ISSUE TITLE
Segmentation fault when running multiple instances of vowpal_wabbit on the same machine

### ISSUE THREAD

**Issue by alantus** [JohnLangford/vowpal_wabbit#944] opened 2016-02-15 11:01 UTC
I'm using vw for simple logistic regression on a machine with 6 CPU's and 16GB mem. When I run only one instance of vw, it works well, but when I run two, sometimes (not always) one of them crashes with segfault. Does vw use some kind of shared resource (temp files, etc) which doesn't work with multiple instances?

**Comment by sharatsc** [comment] 2016-02-15 11:23
Can you provide some more details?
Are you using vw binary or vw library (if so it is python, java or C#
wrapper). Shared resource issue is much more likely in libraries.
If you are using the binary and haven't specified a cache file, it uses
<data_file>.cache as the default cache which might be getting used across
instances. Try specifying different cache files using --cache_file flag.
Also specifying separate model files using -f might help.
regards
Sharat

**Comment by alantus** [comment] 2016-02-15 11:31
I'm using vw binary, version 8.1.1. I'm using automatically created cache (-c), but it has been created before so there is only concurrent reading, which should not be a problem, should it?

**Comment by sharatsc** [comment] 2016-02-15 11:39
It should not be a problem if it's been created before. Can you please
share the command line so I can get a reproducible error?

regards
Sharat

**Comment by alantus** [comment] 2016-02-15 11:57
vw -c --compressed -d A.sh1009.train.vw.scaled.gz --loss_function logistic -f model.2016-02-15T13:50:45+0300 --passes 64 -b 24
I also noticed that it does not crash right after start. It only happened after the first pass had finished.

**Comment by JohnLangford** [comment] 2016-02-15 13:25
Sometimes, these problems are caused by bad hardware.    Have you confirmed
that the same issue does not happen on different machines?

-John

**Comment by arielf** [comment] 2016-02-15 20:19
If both processes run the exact command line specified above then both would write the same cache file. BTW: you don't need to pass `--compressed` for a `*.gz` file (it is implied).
If sharing while rewriting the cache filethis is the root cause, I guess the exact data set is not critical to reproduce.  Can you provide a full (shell command-line sequence with two training commands + data) reproducible example?  Also can you share the log line in /var/log/syslog (if on Ubuntu) or equivalent for the crash?

**Comment by arielf** [comment] 2016-02-15 20:35
I was trying to reproduce here with the following commands:
```
tempDS=/some/big/data.set
vw -c $tempDS --loss_function logistic -f model.1 --passes 64 -b 24 & 
sleep 2;  vw -c $tempDS  --loss_function logistic -f model.2 --passes 64 -b 24
```
If the cache is already there, I get:
```
using cache_file = /some/big/data.set.cache
ignoring text input in favor of cache input
```
If the cache doesn't match the original data-set I get:
```
vw (parser.cc:168): cache version too long, cache file is probably invalid
```

Wan't able to reproduce any crash.  Will need more exact info to reproduce.

**Comment by alantus** [comment] 2016-02-17 07:37
Is there a way to turn on verbosity or debug info? I don't seem to have a 100% effective way to reproduce this myself but it keeps happening from time to time.

**Comment by alantus** [comment] 2016-02-17 08:44
Here's what I found in my /var/log/messages:
Feb 16 21:55:02 alant kernel: [450712.392141] traps: lt-vw[13290] general protection ip:7f315a73bfc7 sp:7f314905de50 error:0 in libvw.so.0.0.0[7f315a6ce000+1d8000]
I'm not 100% sure but this is roughly when the last segfault happened.

**Comment by arielf** [comment] 2016-02-17 20:08
Yes, this looks like a protection fault from vowpal wabbit.
Curious: what system is this?
Looks like `vw` was built with `libtool` (the crashed process executable is `lt-vw`, instead of `vw`).  In some cases (e.g. if this is Ubuntu/Debian), building via `autogen.sh` and libtool is not necessary and has a history of issues. Whenever possible, I would recommend building directly from the original `Makefile` (use `git checkout Makefile` to recover it and then just run `make clean; make` to rebuild).  After that make sure you have a `vw` binary` and no `lt-vw` anywhere.  If this doesn't work in your env, and the only way to build in `autogen.sh`, I'm sorry and have no better ideas.  A fully reproducible example could help.

**Comment by alantus** [comment] 2016-02-18 15:49
It's a Debian system, and I did use autogen.sh to build it. I'll try to rebuild with the original makefile and see if it helps.

**Comment by ekg** [comment] 2016-04-12 15:33
We are also seeing this. It seems to be related to caching, but I also haven't verified this. I will check log files to determine if that's the case.

Is there a possible race when the various vw processes are deciding who should write the cache?

The processes are writing to the cache.writing file even if the original cache file exists. This is very concerning and I don't see how to make it stop.

**Comment by JohnLangford** [comment] 2016-05-07 14:26
There is definitely no locking if multiple VW processes write the same 
cache.  Setups involving that are buggy.  (Multiple reads are fine.)

-John

**Comment by JohnLangford** [comment] 2016-07-25 18:12
I believe "don't write to the same cache file" is the fix here.  Closing, but reopen if you have evidence that is not the case.

**Closed by JohnLangford** 2016-07-25 18:12 UTC
