### ISSUE TITLE
configure: error: Could not find a version of the library!

### ISSUE THREAD

**Issue by puyvqi** [JohnLangford/vowpal_wabbit#1497] opened 2018-06-14 12:12 UTC
i dont know what library i lack ,what should i do .(i just run  ./autogen.sh)
is it necessary to turn all no into yes ?

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking for ANSI C header files... (cached) yes
checking for boostlib >= 1.0... yes
checking whether the Boost::Program_Options library is available... yes
configure: error: Could not find a version of the library!

**Comment by arielf** [comment] 2018-06-14 21:20
Was there a real need to use `autogen.sh` or `configure`?

The [official build instructions](https://github.com/JohnLangford/vowpal_wabbit/blob/master/README.md) suggest to use `autogen.sh` only as a last resort when a simple `make` fails but this is maladvised.

I wouldn't recommend `autogen/automake/configure`, since experience shows people trust it blindly, but it rarely works, because it doesn't cover the _core_ issue of missing missing (dev) libraries+headers, (and possibly other aging reasons). In the old days developers always built from source. Nowadays, they install packages.  If the issue is missing libraries & headers, `autogen.sh` will only make the problem worse: it ends up still missing dependencies _and_  messed-up Makefiles.

I think the instructions should be changed to remove the suggestion to run `autogen.sh`.

Since `autogen.sh` overwrites `Makefile`s, you would have to:
```
    git checkout Makefile */Makefile
```
to ensure you have  a pristine tree with original Makefiles to build correctly.
After that, first get all the dependencies installed (See the Ubuntu instructions as an example).
After that, type `make`.

[Official build instructions in README.md](https://github.com/JohnLangford/vowpal_wabbit/blob/master/README.md)

**Comment by JohnLangford** [comment] 2018-07-01 10:56
Thanks Ariel.  

I think the question here is: Do we want to remove automake entirely?  The upside is fewer build systems making maintenance easier.  You put out an upside of removing false hope.  The downside is that automake handles quite a bit of install related stuff and provides some minor hope of working when make might fail.  

We've been discussing this in NYC as well, in particular with respect using cmake instead since cmake supports windows as well.

**Comment by JohnLangford** [comment] 2018-07-01 10:57
I'm going to close this, as the original issue can't be addressed without further response, but I would like to know your thoughts about build systems.

**Closed by JohnLangford** 2018-07-01 10:57 UTC

**Comment by arielf** [comment] 2018-07-02 01:29
Thanks John

I think we can leave `automake` but change the README.md so it doesn't suggest it so early near the top.  It seems to get people in trouble more than it helps.

`cmake` is a good idea, though it won't solve the issue of missing dependency packages unless it has some check at the top and a clear error on what should be installed first.

I wish I had time to invest in this but these days I don't have much spare time.  I'll be happy to test (on Ubuntu) anything that is contributed by others, tough.  Thanks again.

**Comment by JohnLangford** [comment] 2018-07-02 05:20
Do you want to make a patch?

A key issue here is that we're still using automake for the default release
build.

-John

**Comment by usptact** [comment] 2018-10-23 17:41
Just a thought: what about moving to CMake?

**Comment by JohnLangford** [comment] 2018-10-23 20:08
There are patches brewing around cmake.

-John

**Comment by jackgerrits** [comment] 2018-10-23 20:28
I have a change incoming to move to CMake, I appreciate if you could try the new configuration once it is ready to ensure it fixed your use case.
