### ISSUE TITLE
Visual Studio 2017 Support

### ISSUE THREAD

**Issue by sjjpo2002** [JohnLangford/vowpal_wabbit#1236] opened 2017-05-04 15:30 UTC
I tried to open the solution in VS 2017. It was able to migrate the projects to the MS Build format. But the Wix projects failed to convert. It looks like this is not compatible with VS 2017. 

> setup
Message
..\cs\setup\setup.wixproj: The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=660147&projecttype=930C7802-8A8C-48F9-8165-68863BCCD9DD
setup_bundle
Message
..\cs\setup_bundle\setup_bundle.wixproj: The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=660147&projecttype=930C7802-8A8C-48F9-8165-68863BCCD9DD

**Comment by JohnLangford** [comment] 2017-06-16 22:14
I don't know what the issue is.  @eisber which version of VS are you using to compile VW right now?  (We are planning to sync soon.)

**Comment by JohnLangford** [comment] 2017-06-30 19:58
We are currently on VS 2015.  I'm not super attracted to upgrading because downgrading is much more difficult than vice-versa in general.  

@eisber what are the wixproj's?

**Comment by eisber** [comment] 2017-06-30 20:01
wixproj is used to create the MSI
The current master is on VS2013 for native code (C++) and VS2015 for managed code (C#)

We're in the process of upgrading to VS2015 for both and sub-projects can be compiled on VS2017 using VS2015 backward compatibility.

I advise you not to upgrade to VS2017

**Comment by eisber** [comment] 2017-06-30 20:03
For wix you need to install: http://wixtoolset.org 

Follow https://github.com/JohnLangford/vowpal_wabbit/wiki/Windows-Build

**Comment by JohnLangford** [comment] 2017-06-30 20:04
Closing this for now, reopen if unclear.

**Closed by JohnLangford** 2017-06-30 20:04 UTC

**Comment by adydeshmukh** [comment] 2017-12-08 15:52
I am facing the same issue.
upgrading from VS2013 to VS2017
I have downloaded & installed wix toolset 3.11, but still the projects are unrecognized in VS2017

Any suggestions ?

**Comment by eisber** [comment] 2017-12-08 17:03
You need to install VS 2015 support in VS 2017 and make sure you don’t upgrade the projects.
The wix toolset is only needed if you want to build the MSI installer. If you don’t need that, you can ignore the unloaded project.

Markus

**Comment by adydeshmukh** [comment] 2017-12-11 12:43
I downloaded and installed [WiX Toolset Visual Studio 2017 Extension](https://marketplace.visualstudio.com/items?itemName=RobMensching.WiXToolset) and it worked after a restart for me.

Thanks for responding Marcus
