### ISSUE TITLE
Cpp static analyzer results for VW

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#609] opened 2015-05-04 08:46 UTC
I'v launched one of opensource [static analyzers](http://cppcheck.sourceforge.net/) with source tree (no idea if its params were correctly tuned) to double check my modules. The output was:
```
[../../ml/vowpal_wabbit/cluster/spanning_tree.cc:308]: (error) Memory leak: parent
[../../ml/vowpal_wabbit/cluster/spanning_tree.cc:308]: (error) Memory leak: kid_count
[../../ml/vowpal_wabbit/vowpalwabbit/v_array.h:40]: (error) Common realloc mistake: 'begin' nulled but not freed upon failure
[../../ml/vowpal_wabbit/explore/static/utility.h:168]: (error) Possible null pointer dereference: p
[../../ml/vowpal_wabbit/vowpalwabbit/search.cc:1234]: (error) Possible null pointer dereference: allowed_actions
[../../ml/vowpal_wabbit/vowpalwabbit/search.cc:1241]: (error) Possible null pointer dereference: allowed_actions
[../../ml/vowpal_wabbit/vowpalwabbit/search.cc:1259]: (error) Possible null pointer dereference: allowed_actions
[../../ml/vowpal_wabbit/vowpalwabbit/search.cc:1332]: (error) Possible null pointer dereference: allowed_actions
[../../ml/vowpal_wabbit/vowpalwabbit/search.cc:2353]: (error) Common realloc mistake: 'ec' nulled but not freed upon failure
[../../ml/vowpal_wabbit/vowpalwabbit/search_hooktask.cc:26]: (error) Memory leak: td
```
I've taken a look into v_array.h as it's widely used. The problem isn't critical as VW throws exception in this case and halts anyway, so it's not cause a memory leak. Also it costs one more variable declaration to fix this problem, so i'm not sure if it's worth fixing.   
Anyway,  it would be great, if someone would go throw these problems and make sure everything is fine and comment to this thread.

Regardless of that this topic may be closed at any moment as it's just for info sharing.

**Comment by JohnLangford** [comment] 2015-05-06 14:33
This is nice.  I fixed the memory leak and realloc ones (I think).
Louie, can you look into the utility.h one?  Hal, can you look into the
search.cc and search_hooktask.cc ones?

-John

On Mon, May 4, 2015 at 4:46 AM, Alexander Trufanov <notifications@github.com

**Comment by JohnLangford** [comment] 2015-05-06 15:11
I think utility.h should be fine since c_str() is not supposed to return null pointer. We also don't want the cost of an additional no-op check just to suppress the warning.

Louie
________________________________

**Comment by JohnLangford** [comment] 2015-05-09 04:48
The ones in search.cc are blocked by the assert at the top of the function:

     assert((allowed_actions == nullptr) == (allowed_actions_cnt == 0));

admittedly asserts only fire in debug mode, so I could make this more 
aggressive if you think it's worthwhile.

the one in search_hooktask isn't really a leak.

**Comment by JohnLangford** [comment] 2015-05-09 14:07
Is there a simple change which makes the static analyzer not yell?  If
there isn't something plausible don't worry about it, but if there is it
seems worthwhile.

-John

**Comment by JohnLangford** [comment] 2015-05-09 23:12
This is fixed, just sent a pull request.

**Comment by trufanov-nok** [comment] 2015-05-22 18:04
I've thrown my fork's source into [Coverity](coverity.com) analyser which could be used for free for opensource. Its output quite verbose but some findings have sense. For example: It looks like ` bs_predict_vote` is never freed in [bs_predict_vote()](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/bs.cc#L36)

**Comment by trufanov-nok** [comment] 2015-05-22 19:58
In bfgs.cc in [save_load_regularizer()](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/bfgs.cc#L845) line 884  is unreachable as `read` is always false:
```
if (read) {
...
} else {
...
 if (read && i%2 == 1) // This is the prior mean
all.reg.weight_vector[(i/2*stride)] = *v;
}
```

**Comment by trufanov-nok** [comment] 2015-05-22 20:10
There seems to be a memory leak in kernel_svm.cc' [predict()](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/kernel_svm.cc#L387):
`svm_example* sec` is callocated and never freed.

**Comment by JohnLangford** [comment] 2015-05-23 21:30
Confirmed, and fixed.

Alekh, I'd suggest adding a test example for the predict case. Also, 
there is quite a bit of alloc/free going on.  It would be much better if 
that sort of thing did not happen.

-John

**Comment by JohnLangford** [comment] 2015-05-23 21:32
It looks like this can just be cut. Doing so.

-John

**Comment by JohnLangford** [comment] 2015-05-23 21:35
Good catch, thanks.  It should be fixed now.

-John

**Comment by JohnLangford** [comment] 2015-05-23 21:38
I believe the other issues that you started with are also fixed or nonissues.  I'll close this for now.

**Closed by JohnLangford** 2015-05-23 21:38 UTC
