### ISSUE TITLE
== FATAL: vw subprocess failed (status=1)

### ISSUE THREAD

**Issue by TylerL-uxai** [JohnLangford/vowpal_wabbit#1313] opened 2017-08-15 09:21 UTC
When I add --interactions ff to VW_ARGS from a fresh clone of https://github.com/arielf/weight-loss it gives me this error:

```
lifestyle-csv2vw 3 tyler.csv | sort-by-abs > tyler.train
vw-varinfo2 -k --loss_function quantile --progress 1 --bootstrap 7 -l 0.05 --l2 1.85201e-08 -c --passes 4 --interactions ff  tyler.train | tee scores.txt
== FATAL: vw subprocess failed (status=1): '['vw', '-f', '/var/folders/hl/jkwl1vnj45x0vtshztmps1900000gq/T/tmpyXtazL.vwmodel', '--audit', '-k', '--loss_function', 'quantile', '--progress', '1', '--bootstrap', '7', '-l', '0.05', '--l2', '1.85201e-08', '-c', '--passes', '4', '--interactions', 'ff', 'tyler.train']'
```

I know I can get this working, but I never git committed it. Not sure how to fix it.

Edit: Only change to the clone of weight-loss is to add an f namespace
line 80 of lifestyle-csv2vw should say            
```
 printf "%.2f |f @sum_factors\n", $sum_gain;
```

(notice the |f )

**Comment by arielf** [comment] 2017-08-15 18:05
This means that `vw` itself refused/failed to run after your change(s) for some reason.

Try to run the command itself (printed after the status=1) stripped of the python list annotation, and see why.  It should print the error.

When I try to reproduce it looks like some bug in `vw --interactions ... --passes ... --audit`.
it crashes after some time saying:
```
Segmentation fault (core dumped) 
```
Sometimes I also see `vw: std::bad_alloc`

So if you want help on this, you should open an issue with vowpal wabbit itself.
This will require some work from you. Rather than sending developers here, You should provide a *minimal* example (unrelated to, and stripped of all the added baggage of this repo) reproducing the problem.

The way to create a minimal example is to start with your input and `vw` command, make sure the crash happens, then remove options one by one until it no longer crashes. Finally add the last one you removed back.  Same thing with the input, remove lines until you get the smallest data that still makes `vw` crash.  Finally post your command and data, there (vowpal wabbit repo), not here.

To help you, I am able to reproduce this SEGV with only one line of input, and a much simplified command:
```
vw  -k --audit --interactions ff -c --passes 2 z.train
```
HTH.

**Comment by arielf** [comment] 2017-08-15 18:06
I also checked in a little change to `vw-varinfo2` to make the fatal error more friendly.

**Closed** 2017-08-15 18:18 UTC
