### ISSUE TITLE
Alignment in output

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#525] opened 2015-02-18 21:21 UTC
Perhaps I've broken something in my fork, but I'm getting progress output in form of:
```
Reading datafile = train-sets/rcv1_small.dat
num sources = 1
average    since         example     example  current  current  current
loss       last          counter      weight    label  predict features
1.000000   1.000000          1      1.0    -1.0000   0.0000      128
0.893728   0.787455          2      2.0    -1.0000  -0.1126       44
0.905122   0.916517          4      4.0    -1.0000  -0.1701      190
0.924790   0.944458          8      8.0     1.0000  -0.0231       34
0.894742   0.864695         16     16.0     1.0000   0.0065       43
0.875196   0.855650         32     32.0    -1.0000   0.0423       47
0.838072   0.800947         64     64.0     1.0000   0.0619       54
0.754589   0.671106        128    128.0    -1.0000  -0.2779       67
0.662491   0.570393        256    256.0     1.0000   0.6543       86
0.564488   0.466484        512    512.0    -1.0000  -0.8828      104

finished run
number of examples per pass = 1000

```
The columns alignment is broken. It was like 

```
Reading datafile = train_freq.vw
num sources = 1
average    since         example     example  current  current       
loss       last          counter      weight    label  predict     
0.775936   0.775936            1         1.0  -1.0000   0.1592      
0.728623   0.681310            2         2.0  -1.0000  -0.0238       
0.708393   0.688163            4         4.0  -1.0000  -0.0018       
0.737389   0.766386            8         8.0  -1.0000   0.2023    
0.796014   0.854638           16        16.0  -1.0000   0.5368     
0.866274   0.936533           32        32.0  -1.0000   1.0178    
0.947102   1.027930           64        64.0  -1.0000   1.0452     
1.061943   1.176785          128       128.0  -1.0000   1.2128     
1.208501   1.355059          256       256.0   1.0000   0.6986    
1.211329   1.214156          512       512.0  -1.0000   0.5613     
1.032622   0.853914         1024      1024.0  -1.0000  -0.3099     
0.886021   0.739420         2048      2048.0  -1.0000   0.2083    
0.768442   0.650864         4096      4096.0  -1.0000  -0.8474    

```

Do you observe the same?

**Comment by JohnLangford** [comment] 2015-02-18 21:27
Yes.

-John

**Comment by arielf** [comment] 2015-02-18 23:08
Wasn't you Alex.
The column alignment regression happened between 7.8 and 7.9.
Looking now.

**Comment by arielf** [comment] 2015-02-18 23:47
According to git bisect, this commit caused the misalignment:
```
a13d55a0b46c1d45e949443965d2dd9173108d06 is the first bad commit
commit a13d55a0b46c1d45e949443965d2dd9173108d06
Date:   Sat Jan 10 23:03:20 2015 -0500

    partially unifed printing
```

It is a dilemma: on one hand having smaller output is nicer, OTOH on big inputs the 'example counter' and 'example weight' columns tend to grow the most, and cause misalignment.  At one point, I was about to add a char to the width for a 10x more capacity.  Wish we could use %g here and limit precision without sacrificing neatness, but it seems to have a bug in that it doesn't respect the printf width spec.

**Comment by JohnLangford** [comment] 2015-02-19 01:24
Perhaps we should lose the low order precision by abbreviating with K/M/G/T?

-John

**Comment by arielf** [comment] 2015-02-23 19:03
This is a nice idea, but I feel a bit uncomfortable with making numbers non numeric. E.g: this may break scripts which try to plot loss vs example number.  Would it be ok if I just fix it to behave as it was before?   BTW: this regression wasn't caught by reference stderr outputs because the test suite ignores white-space diffs.

**Comment by bscottm** [comment] 2015-02-24 18:05
Perhaps remove the remaining vestiges of C stdio?

**Comment by arielf** [comment] 2015-03-03 06:33
This is fixed now and can be closed.

**Closed** 2015-04-17 18:26 UTC
