### ISSUE TITLE
How to set termination threshold?

### ISSUE THREAD

**Issue by robbine** [JohnLangford/vowpal_wabbit#1054] opened 2016-07-25 12:55 UTC
I tried termination option and got this error
vw: unknown option termination
is it deprecated?

**Comment by arielf** [comment] 2016-07-25 17:35
There's no generic --termination option to vw.

When you run multiple passes: `--passes <N>` with the default holdout, it will do early termination on the number of passes (controlled with `--early_terminate`):
```
 --early_terminate arg          Specify the number of passes tolerated when
                                                 holdout loss doesn't decrease before early
```

`--termination` is not deprecated, but it is applicable/limited to `--bfgs` only.

See more detail in [vw command line arguments](https://github.com/JohnLangford/vowpal_wabbit/wiki/Command-line-arguments)

Unfortunately, option combos in `vw` are not very user friendly...
The problem is that there are well over 100 options in total, and that many of them are only implemented for certain reductions so if you don't activate the relevant reduction code, they aren't there:

Excerpt from:
```
vw --quiet --bfgs -c --passes 2 --help
...

LBFGS options:
  --hessian_on                       use second derivative in line search
  --mem arg (=15)                    memory in bfgs
  --termination arg (=0.00100000005) Termination threshold
```

And yes, it would be nice to have a general termination option, even for one pass.

**Comment by JohnLangford** [comment] 2016-07-25 19:33
What would a termination option look like?

**Comment by arielf** [comment] 2016-07-25 20:56
My thinking was along:
```
    --termination <threshold>         <threshold> is a floating point number
```
where `vw` stops accepting input and finalizes the model iff avg-loss becomes equal or less than <threshold>. 

From the end user perspective, there's no reason to limit this option to `--bfgs` only. 

(Comparing this to 'loss since-last' makes much less sense since that's a very volatile number.)

**Comment by robbine** [comment] 2016-07-26 02:30
So if I set -passes 20 and --early_terminate 10.
Then vw will terminate after 10 passes when holdout loss doesn't decrease, right?

**Comment by arielf** [comment] 2016-07-26 06:38
Yes, [as explained in the command-line args doc](https://github.com/JohnLangford/vowpal_wabbit/wiki/Command-line-arguments)

```
--early_terminate <arg>
                         Specify the number of passes tolerated when
                          holdout loss doesn't decrease before early
                          termination. Default is 3
```

When you run `vw` with multiple passes (and no `--holdout_off`) it will tell you how many passes were actually used, and it will print the holdout loss, so you can see exactly when (in which passes) the (holdout) loss stopped decreasing.  holdout loss should start increasing with seen-examples over-fit vs unseen examples.  You can also control the holdout period (1 in <N> examples) with `--holdout_period <N>`)

**Comment by JohnLangford** [comment] 2016-08-09 18:57
Closing this for now.  I'm hesitant to go with a termination threshold in general, because users typically want to maximize accuracy, constrained only by computation (which check pointing handles well).  The termination criteria in bfgs is a throwback to the optimization view where we do not have a holdout set.

**Closed by JohnLangford** 2016-08-09 18:57 UTC
