### ISSUE TITLE
How to extract output policy from contextual bandit?

### ISSUE THREAD

**Issue by MarcinKosinski** [JohnLangford/vowpal_wabbit#511] opened 2015-02-10 17:21 UTC
I am posting this question because I can not find solution on wiki :/

I am running your [example](https://github.com/JohnLangford/vowpal_wabbit/wiki/Contextual-Bandit-Example) for contextual bandit, on example data as yours:
````
1:2:0.4 | a c  
3:0.5:0.2 | b d  
4:1.2:0.5 | a b c  
2:1:0.3 | b c  
3:1.5:0.7 | a d  
````

with command as your suggestions:
````
vw -d train.dat --cb 4 --cb_type dr -f traindModel
````

and I wonder how to extract the policy from this command and how to interpret it then?

**Comment by MarcinKosinski** [comment] 2015-02-11 10:26
And then I go
````
vw -d train.dat --invert_hash traindModel
````
and recieve such output
````
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = ../r-mkosinski/train.dat
num sources = 1
average    since         example     example  current  current  current
loss       last          counter      weight    label  predict features
1.000000   1.000000          1      1.0     1.0000   0.0000        3
4.439352   7.878704          2      2.0     3.0000   0.1931        3
4.457758   4.476164          4      4.0     2.0000   1.4285        3

finished run
number of examples per pass = 5
passes used = 1
weighted example sum = 5
weighted label sum = 13
average loss = 4.14973
best constant = 2.6
total feature number = 16
````

**Comment by JohnLangford** [comment] 2015-02-13 19:28
In general you "extract" the policy by applying it to new examples.  What
you see with invert_hash is based on the stored model, which is in a sparse
format.  Hence missing entry => parameter value 0.  The precise semantics
of the different versions of "d" are highly dependent on the parameters
that you train with.  Some of these are due to the reduction to
cost-sensitive classification while others are due to double robust
regression.  Which... depends in a critical way on the code.

-John

**Comment by JohnLangford** [comment] 2015-02-13 19:32
Closing for now.

**Closed by JohnLangford** 2015-02-13 19:32 UTC

**Comment by martinpopel** [comment] 2015-02-13 19:55
See also http://stackoverflow.com/questions/28453591/how-to-extract-output-policy-from-contextual-bandit-in-vowpall-wabbit/

**Comment by JohnLangford** [comment] 2015-02-13 20:20
Oh, great.  Thanks Martin.

-John
