### ISSUE TITLE
on 8.3.1 --cubic is not working correctly (according to vw-varinfo and vw --audit)

### ISSUE THREAD

**Issue by Benedicto** [JohnLangford/vowpal_wabbit#1237] opened 2017-05-04 21:09 UTC
Execute the following 2 commands

```bash
echo "-1 |NAME someone is |WHERE beijing sanfran |LIVE together" > example.train
vw-varinfo -v --cubic NWL example.train
```

Expected: cartesian between the 3 namespaces are returned
Actual: see below
```bash
FeatureName                                                                 	   HashVal   MinVal   MaxVal    Weight   RelScore
Constant                                                                    	    116060     0.00     0.00   -0.0794      0.00%
LIVE^together                                                               	    134012     0.00     1.00   -0.0794   -100.00%
NAME^is                                                                     	    129601     0.00     1.00   -0.0794   -100.00%
NAME^is*WHERE^beijing*LIVE^together                                         	    126853     0.00     0.00   -0.0794   -100.00%
NAME^is*WHERE^beijing*NAME^someone*WHERE^beijing*LIVE^together              	    114710     0.00     0.00   -0.0794   -100.00%
NAME^is*WHERE^beijing*NAME^someone*WHERE^beijing*WHERE^sanfran*LIVE^together	    125061     0.00     0.00   -0.0794   -100.00%
NAME^is*WHERE^beijing*WHERE^sanfran*LIVE^together                           	    145174     0.00     0.00   -0.0794   -100.00%
NAME^someone                                                                	    121866     0.00     1.00   -0.0794   -100.00%
WHERE^beijing                                                               	     78480     0.00     1.00   -0.0794   -100.00%
WHERE^sanfran                                                               	     18557     0.00     1.00   -0.0794   -100.00%
```

**Comment by arielf** [comment] 2017-05-04 21:30
It is a "known" bug in vw-varinfo.

`vw-varinfo` knows too much about `vw` options and actually semi-implements `-q` crossing internally, but since it was written before `--cubic` it didn't know about `--cubic`.  This code won't be fixed since the state of the code is hopeless.

Two options:
- Use `vw --invert_hash ...` and use the normalize the weights to -100% - +100%
- Try `vw-varinfo2`  https://github.com/arielf/weight-loss/blob/master/vw-varinfo2
  (and be aware that `vw-varinfo2` doesn't support multi-class)

**Comment by Benedicto** [comment] 2017-05-04 22:28
@arielf It is happening not only with vw-varinfo, but also vw. Try the following
```bash
echo "-1 |NAME someone is |WHERE beijing sanfran |LIVE together" > example.train
vw --audit --cubic NWL example.train
```
I'm seeing output containing the following:
```bash
NAME^someone*WHERE^beijing*WHERE^sanfran*LIVE^together:125061:1:0@0	
NAME^someone*WHERE^beijing*NAME^is*WHERE^beijing*LIVE^together:126853:1:0@0
```
Notice the two WHERE and two NAME. It definitely looks like something is wrong with --cubic itself

**Comment by arielf** [comment] 2017-05-04 22:35
@Benedicto  thanks!

Sorry, I had the knee-jerk reaction to he mention of `vw-varinfo` since I know too well how broken and fragile it is`.

So now that `vw-varinfo` is out of the picture, this looks like a serious regression in `vw`.

Time to add a nice `--cubic` test to the test suite and a `git bisect` to find what broke this :(

**Comment by arielf** [comment] 2017-05-04 23:47
Did some preliminary testing.

Looks like this issue isn't very new.

The earliest I can see it appear is almost a year ago, in an executable I saved around 2016-07-25
```
$ ./Regressions/cubic ~/bin/vw-8.*
=== testing ~/bin/vw-8.20150902
=== testing ~/bin/vw-8.20150927
=== testing ~/bin/vw-8.20151002
=== testing ~/bin/vw-8.20151005
=== testing ~/bin/vw-8.20151013
=== testing ~/bin/vw-8.20151019
=== testing ~/bin/vw-8.20151101
=== testing ~/bin/vw-8.20151121
=== testing ~/bin/vw-8.20151122
=== testing ~/bin/vw-8.20151204
=== testing ~/bin/vw-8.20160725
Bug in ~/bin/vw-8.20160725: cubic feature 'A^1[*^]B^3[*^]C^4' missing in /tmp/cubic-test.ih
```

/tmp/cubic-test.ih contains:

```
Version 8.2.0
Id
Min label:0
Max label:1
bits:18
lda:0
0 ngram:
0 skip:
options:
Checksum: 3773470323
:0
A^1:63439:0.0642374
A^1*B^2*B^3*C^4:13183:0.0642374
A^1*B^2*B^3*C^5:13152:0.0642374
A^1*B^2*B^3*C^6:13153:0.0642374
A^1*B^2*C^4:12556:0.0642374
A^1*B^2*C^5:12563:0.0642374
A^1*B^2*C^6:12562:0.0642374
B^2:158348:0.0642374
B^3:158349:0.0642374
C^4:65167:0.0642374
C^5:65168:0.0642374
C^6:65169:0.0642374
Constant:116060:0.0642374
```

Note how it crosses B^2 and B^3 (despite not being asked to generate interactions inside a name-space) and how indeed 'A^1*B^3*C^4' is missing

**Comment by arielf** [comment] 2017-05-05 01:03
More findings, and good news.

I find the issue is gone since at least 8.3.2 (April 2017).

So seems like this is a past regression.  8.3.1 and earlier versions.

Anyway: at least as of 2017-04-17, Version 8.3.2 - the issue is fixed for sure.
Here's the inverted_hash model in 8.3.2:
```
Version 8.3.2
Id
Min label:0
Max label:1
bits:18
lda:0
0 ngram:
0 skip:
options: --cubic ABC
Checksum: 881798891
:0
A^1:63439:0.0642374
A^1*B^2*C^4:12556:0.0642374
A^1*B^2*C^5:12563:0.0642374
A^1*B^2*C^6:12562:0.0642374
A^1*B^3*C^4:13183:0.0642374
A^1*B^3*C^5:13152:0.0642374
A^1*B^3*C^6:13153:0.0642374
B^2:158348:0.0642374
B^3:158349:0.0642374
C^4:65167:0.0642374
C^5:65168:0.0642374
C^6:65169:0.0642374
Constant:116060:0.0642374
```

Almost minimal example for `--cubic` can be tested with:
```
echo "1 'cubic_test|A 1 |B 2 3 |C 4 5 6" | vw --cubic --invert_hash cubic.ih
```

If `cubic.ih` is missing the following 3 cubic features, we have the bug:
```
    A^1.B^3.C^4
    A^1.B^3.C^5
    A^1.B^3.C^6
```
(Note: I use `.` in lieu of either the old style `^` or the newer style `*` interaction separator. It works well  as a generic regex)

Here's a bash script for testing:
```
#!/bin/bash

NAME='cubic-test'

DataSet=/tmp/${NAME}.train
IH=/tmp/${NAME}.ih

VW=vw
Errors=0

warn() {
    echo "$@" 1>&2
    Errors=$(($Errors+1))
}

die() {
    warn "$@"
    exit 1
}

verify_cubic_ABC() {
    vw="$1"
    ih="$2"

    Errors=0

    # Run vw
    echo === Testing $vw
    /bin/rm -f "$DataSet" "$ih"
    echo "1 'cubic_test|A 1 |B 2 3 |C 4 5 6" > $DataSet
    $vw --quiet --cubic ABC -d "$DataSet" --invert_hash "$ih"

    # Verify single features existence
    for f1 in 'A^1' 'B^2' 'B^3' 'C^4' 'C^5' 'C^6'; do
        grep -q "$f1:" $ih || \
            warn "feature '$f1' not found in invert_hash"
    done

    # Verify cubic features existence
    f1='A^1'
    for f2 in 'B^2' 'B^3'; do
        for f3 in 'C^4' 'C^5' 'C^6'; do
            cubic_feature="$f1.$f2.$f3"
            grep -q "^$cubic_feature:" $ih || \
                warn "$vw: cubic feature '$cubic_feature' missing in $ih"
        done
    done
    case $Errors in
        (0) : ;;
        (*) warn "$vw: $Errors errors"
            ;;
    esac
}

#
# main
#

for vw in "$@"; do
    verify_cubic_ABC "$vw" "$IH"
done
```

And the following recent two executables don't have the issue:
```
 === Testing ~/bin/vw-8.20170412
 === Testing ~/bin/vw-8.20170504
```

**Comment by Benedicto** [comment] 2017-05-05 11:27
Thanks, @arielf .
Where can I get 8.3.2? I don't see a tag with 8.3.2 in this repo.
Also, any chance we can push a new formula to brew? I installed vw through brew and the only version available there is 8.3.1

**Comment by arielf** [comment] 2017-05-05 16:14
@Benedicto - Sorry I'm not a brew expert.
I suggest contacting the person who did the current brew package and ask to refresh from latest source.
You may also build from source by cloning this repo and running a `make` at the top dir.

**Comment by JohnLangford** [comment] 2017-06-16 22:13
@Benedicto , @arielf thank you for the detective work and the test case :-)

**Closed by JohnLangford** 2017-06-16 22:13 UTC
